
-- ===============================
-- HỆ THỐNG ĐẶT PHÒNG - CHỈ HỖ TRỢ KHÁCH HÀNG VÀ KHÁCH SẠN
-- ===============================

-- 1. NGƯỜI DÙNG
CREATE TABLE NGUOIDUNG (
    ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100),
    MATKHAU VARCHAR2(100) NOT NULL,
    HOTEN VARCHAR2(100),
    LOAITK VARCHAR2(20) CHECK (LOAITK IN ('KHACHHANG', 'KHACHSAN', 'ADMIN'))
);

-- 2. KHÁCH HÀNG
CREATE TABLE KHACHHANG (
    ID NUMBER PRIMARY KEY REFERENCES NGUOIDUNG(ID) ON DELETE CASCADE,
    CCCD VARCHAR2(20),
    NGAYSINH DATE
);

-- 3. KHÁCH SẠN (TRƯỚC ĐÂY LÀ DOANHNGHIEP)
CREATE TABLE KHACHSAN (
    ID NUMBER PRIMARY KEY REFERENCES NGUOIDUNG(ID) ON DELETE CASCADE,
    TENDN VARCHAR2(100),
    DIACHI VARCHAR2(200),
    MOTA CLOB
);

-- 4. NHÂN VIÊN
CREATE TABLE NHANVIEN (
    ID NUMBER PRIMARY KEY REFERENCES NGUOIDUNG(ID) ON DELETE CASCADE,
    BOPHAN VARCHAR2(50)
);

-- 5. PHÒNG
CREATE TABLE PHONG (
    ID NUMBER PRIMARY KEY,
    KHACHSAN_ID NUMBER REFERENCES KHACHSAN(ID) ON DELETE CASCADE,
    LOAIPHONG VARCHAR2(50),
    GIA NUMBER,
    MOTA CLOB,
    TONGSOLUONG NUMBER,
    ANH1 BLOB,
    ANH2 BLOB,
    ANH3 BLOB
);
ALTER TABLE PHONG
  ADD (NGAY_DANG DATE);

-- 6. ĐẶT PHÒNG
CREATE TABLE DATPHONG (
    ID NUMBER PRIMARY KEY,
    KHACHHANG_ID NUMBER REFERENCES KHACHHANG(ID) ON DELETE CASCADE,
    PHONG_ID NUMBER REFERENCES PHONG(ID) ON DELETE CASCADE,
    NGAYNHAN DATE,
    NGAYTRA DATE,
    SL NUMBER,
    TRANGTHAI VARCHAR2(20)
);

-- 7. THANH TOÁN
CREATE TABLE THANHTOAN (
    ID NUMBER PRIMARY KEY, -- Tham chiếu tới ID của DATPHONG
    NGAY_GIAODICH DATE DEFAULT SYSDATE,
    SOTIEN NUMBER(10, 2),
    SOTHE VARCHAR2(4 BYTE), -- Lưu 4 số cuối
    TEN_CHUTHE VARCHAR2(50),
    FOREIGN KEY (ID) REFERENCES DATPHONG(ID)
);

-- 8. HỎI ĐÁP
CREATE TABLE HOIDAP (
    ID NUMBER PRIMARY KEY,
    KHACHHANG_ID NUMBER REFERENCES KHACHHANG(ID) ON DELETE CASCADE,
    NOIDUNG CLOB,
    NGAYGUI DATE DEFAULT SYSDATE,
    NHANVIEN_ID NUMBER REFERENCES NHANVIEN(ID) ON DELETE CASCADE,
    TRALOI CLOB,
    NGAYTRALOI DATE
);

-- ===============================
-- SEQUENCE + TRIGGER
-- ===============================
CREATE SEQUENCE SEQ_NGUOIDUNG_ID START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_AUTO_ID_NGUOIDUNG
BEFORE INSERT ON NGUOIDUNG
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_NGUOIDUNG_ID.NEXTVAL INTO :NEW.ID FROM dual;
  END IF;
END;
/

-- 1. Tạo sequence cho PHONG.ID
CREATE SEQUENCE seq_phong
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- 2. Tạo trigger tự động gán ID trước khi insert
CREATE OR REPLACE TRIGGER trg_phong_id
  BEFORE INSERT ON PHONG
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := seq_phong.NEXTVAL;
  END IF;
END;
/

-- ===============================
-- DỮ LIỆU MẪU
-- ===============================
select * from NGUOIDUNG
select * from PHONG
-- NGUOIDUNG
INSERT INTO NGUOIDUNG(ID, EMAIL, MATKHAU, HOTEN, LOAITK) VALUES (1, 'kh1@example.com', '123', 'Nguyễn Văn A', 'KHACHHANG');
INSERT INTO NGUOIDUNG(ID, EMAIL, MATKHAU, HOTEN, LOAITK) VALUES (2, 'hotel1@example.com', '456', 'Sunrise Hotel', 'KHACHSAN');
INSERT INTO NGUOIDUNG(ID, EMAIL, MATKHAU, HOTEN, LOAITK) VALUES (3, 'admin@example.com', 'adminpass', 'Quản trị', 'ADMIN');

-- KHACHHANG
INSERT INTO KHACHHANG(ID, CCCD, NGAYSINH) VALUES (1, '012345678', TO_DATE('1990-01-01', 'YYYY-MM-DD'));

-- KHACHSAN
INSERT INTO KHACHSAN(ID, TENDN, DIACHI, MOTA) VALUES (2, 'Sunrise Hotel', '123 Beach Road', 'Khách sạn nghỉ dưỡng cao cấp');

-- NHANVIEN
INSERT INTO NHANVIEN(ID, BOPHAN) VALUES (3, 'Quản trị hệ thống');

-- PHONG
INSERT INTO PHONG(ID, KHACHSAN_ID, TENPHONG, LOAIPHONG, GIA, MOTA, SOLUONGCONLAI, TONGSOLUONG, NGAYDANG) VALUES
(1, 2, 'Deluxe 101', 'DELUXE', 2000000, 'Phòng rộng, có ban công, view biển', 5, 5, SYSDATE);

-- DATPHONG
INSERT INTO DATPHONG(ID, KHACHHANG_ID, PHONG_ID, NGAYNHAN, SONGAY, TRANGTHAI) VALUES
(1, 1, 1, TO_DATE('2025-06-01', 'YYYY-MM-DD'), 2, 'CHOTHANHTOAN');

-- THANHTOAN
INSERT INTO THANHTOAN(ID, KHACHHANG_ID, MADON, SOTIEN, PHUONGTHUC, TRANGTHAI, NGAYGIAODICH, MAGIAODICH_DOITAC) VALUES
(1, 1, 1, 4000000, 'MOMO', 'DATHANHTOAN', SYSDATE, 'TXN001');

-- HOIDAP
INSERT INTO HOIDAP(ID, KHACHHANG_ID, NOIDUNG, NGAYGUI, NHANVIEN_ID, TRALOI, NGAYTRALOI) VALUES
(1, 1, 'Khách sạn còn phòng không?', SYSDATE, 3, 'Còn, quý khách có thể đặt ngay.', SYSDATE);

-- ===============================
-- COMMIT
-- ===============================
COMMIT;