/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login_And_SignUp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class SignUpKhachHang extends javax.swing.JFrame {

    private String fullname;
    private String username;
    private String password;
    
    public SignUpKhachHang(String fullname, String username, String password) {
        initComponents();
        this.fullname=fullname;
        this.username=username;
        this.password=password;
    }
    
    public SignUpKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Nen_tren = new javax.swing.JPanel();
        Nen_duoi = new javax.swing.JPanel();
        Label_Information_Fill = new javax.swing.JLabel();
        CCCD_label = new javax.swing.JLabel();
        CCCD_Fill = new javax.swing.JTextField();
        BirthDay_label = new javax.swing.JLabel();
        example_BirthDay = new javax.swing.JLabel();
        Check_Condition = new javax.swing.JCheckBox();
        SignUp_Confirm = new javax.swing.JButton();
        BirthDay_Fill = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(244, 244, 242));

        Nen_tren.setBackground(new java.awt.Color(0, 102, 102));
        Nen_tren.setPreferredSize(new java.awt.Dimension(650, 105));

        javax.swing.GroupLayout Nen_trenLayout = new javax.swing.GroupLayout(Nen_tren);
        Nen_tren.setLayout(Nen_trenLayout);
        Nen_trenLayout.setHorizontalGroup(
            Nen_trenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        Nen_trenLayout.setVerticalGroup(
            Nen_trenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        Nen_duoi.setBackground(new java.awt.Color(0, 102, 102));
        Nen_duoi.setPreferredSize(new java.awt.Dimension(650, 105));

        javax.swing.GroupLayout Nen_duoiLayout = new javax.swing.GroupLayout(Nen_duoi);
        Nen_duoi.setLayout(Nen_duoiLayout);
        Nen_duoiLayout.setHorizontalGroup(
            Nen_duoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        Nen_duoiLayout.setVerticalGroup(
            Nen_duoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        Label_Information_Fill.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label_Information_Fill.setForeground(new java.awt.Color(0, 102, 102));
        Label_Information_Fill.setText("NHẬP THÔNG TIN CÁ NHÂN");

        CCCD_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CCCD_label.setForeground(new java.awt.Color(0, 0, 0));
        CCCD_label.setText("Căn Cước Công Dân:");

        CCCD_Fill.setBackground(new java.awt.Color(249, 249, 249));
        CCCD_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CCCD_Fill.setForeground(new java.awt.Color(102, 102, 102));
        CCCD_Fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCCD_FillActionPerformed(evt);
            }
        });

        BirthDay_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BirthDay_label.setForeground(new java.awt.Color(0, 0, 0));
        BirthDay_label.setText("Ngày Sinh:");

        example_BirthDay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        example_BirthDay.setForeground(new java.awt.Color(102, 102, 102));
        example_BirthDay.setText("VD: 16/02/2005");

        Check_Condition.setBackground(new java.awt.Color(249, 249, 249));
        Check_Condition.setForeground(new java.awt.Color(102, 102, 102));
        Check_Condition.setText("Đồng ý cung cấp thông tin của tôi trong quá trình sử dụng.");
        Check_Condition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_ConditionActionPerformed(evt);
            }
        });

        SignUp_Confirm.setBackground(new java.awt.Color(0, 102, 102));
        SignUp_Confirm.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SignUp_Confirm.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Confirm.setText("Đăng Ký");
        SignUp_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ConfirmActionPerformed(evt);
            }
        });

        BirthDay_Fill.setBackground(new java.awt.Color(249, 249, 249));
        BirthDay_Fill.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nen_tren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nen_duoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Label_Information_Fill))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(example_BirthDay)
                            .addComponent(CCCD_label)
                            .addComponent(CCCD_Fill)
                            .addComponent(BirthDay_label)
                            .addComponent(Check_Condition)
                            .addComponent(BirthDay_Fill, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignUp_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Nen_tren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(Label_Information_Fill)
                .addGap(56, 56, 56)
                .addComponent(CCCD_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CCCD_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BirthDay_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirthDay_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(example_BirthDay)
                .addGap(18, 18, 18)
                .addComponent(Check_Condition)
                .addGap(36, 36, 36)
                .addComponent(SignUp_Confirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Nen_duoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Check_ConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_ConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check_ConditionActionPerformed

    private void SignUp_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ConfirmActionPerformed
        // TODO add your handling code here:
        
        // Lấy thông tin người đăng ký nhập
        String cccd       = CCCD_Fill.getText();
        String ngaysinh   = BirthDay_Fill.getText();

        if (!Check_Condition.isSelected()) {
            JOptionPane.showMessageDialog(this,
                "Bạn phải đồng ý với điều khoản để đăng ký!",
                "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (cccd.isEmpty() || ngaysinh.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Bạn phải điền đầy đủ thông tin!",
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parse ngày sinh từ String sang java.sql.Date
        java.sql.Date NgaySinh;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date utilDate = sdf.parse(ngaysinh);
            NgaySinh = new java.sql.Date(utilDate.getTime());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this,
                "Vui lòng nhập ngày sinh đúng định dạng dd/MM/yyyy",
                "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sqlNguoiDung = 
            "INSERT INTO booking_app.NGUOIDUNG (MATKHAU, HOTEN, EMAIL, LOAITK) " +
            "VALUES (?, ?, ?, 'KHACHHANG')";
        String sqlKhach = 
            "INSERT INTO booking_app.KHACHHANG (ID, CCCD, NGAYSINH) VALUES (?, ?, ?)";

        Connection conn = null;
        try {
            conn = OracleDataBase_Connection.getConnection("nguoidung_user", "12345678");
            conn.setAutoCommit(false);

            // 1. Insert NGUOIDUNG và lấy ID sinh tự động
            int newId;
            try (PreparedStatement stmt1 = conn.prepareStatement(
                     sqlNguoiDung, new String[]{"ID"})) {
                stmt1.setString(1, this.password);
                stmt1.setString(2, this.fullname);
                stmt1.setString(3, this.username);
                stmt1.executeUpdate();

                try (ResultSet rs = stmt1.getGeneratedKeys()) {
                    if (rs.next()) {
                        newId = rs.getInt(1);
                    } else {
                        throw new SQLException("Không lấy được ID từ NGUOIDUNG");
                    }
                }
            }

            // 2. Insert KHACHHANG với ID vừa lấy được
            try (PreparedStatement stmt2 = conn.prepareStatement(sqlKhach)) {
                stmt2.setInt(1, newId);
                stmt2.setString(2, cccd);
                stmt2.setDate(3, NgaySinh);
                stmt2.executeUpdate();
            }

            conn.commit();
            JOptionPane.showMessageDialog(this,
                "Đăng ký thành công!", "Thành công",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            try {
                if (conn != null) conn.rollback();
            } catch (SQLException ex) {
            }
            JOptionPane.showMessageDialog(this,
                "Đăng ký thất bại: " + e.getMessage(),
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conn != null) conn.close();
            } catch (SQLException ex) {
            }
        }

    }//GEN-LAST:event_SignUp_ConfirmActionPerformed

    private void CCCD_FillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCCD_FillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCCD_FillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JTextField BirthDay_Fill;
    private javax.swing.JLabel BirthDay_label;
    private javax.swing.JTextField CCCD_Fill;
    private javax.swing.JLabel CCCD_label;
    private javax.swing.JCheckBox Check_Condition;
    private javax.swing.JLabel Label_Information_Fill;
    private javax.swing.JPanel Nen_duoi;
    private javax.swing.JPanel Nen_tren;
    private javax.swing.JButton SignUp_Confirm;
    private javax.swing.JLabel example_BirthDay;
    // End of variables declaration//GEN-END:variables
}
