/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Component;

import DAO.KhachSan_DAO;
import MODEL.KHACHSAN;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.text.SimpleDateFormat;
import java.util.Date;


public class accKhachSan extends javax.swing.JPanel {
    private JPanel parent;
    private CardLayout cardLayout;
    private KHACHSAN ks;
   
    public accKhachSan() {
        initComponents();
    }
    public accKhachSan(String email) {
        initComponents();
        setText(email);
    }
    public void setText(String email){
        KhachSan_DAO ksdao = new KhachSan_DAO();
        ks = ksdao.select(email);

        emailTextField.setText(ks.getEMAIL());
        tenDNTextField.setText(ks.getTENDN());
        nameTextField.setText(ks.getHOTEN());
        tenBank.setSelectedItem(ks.getBANK());
        motaTextField.setText(ks.getMOTA());
        stkTextField.setText(ks.getSTK());
        

        
    }
    public accKhachSan(JPanel parent, CardLayout cardLayout,String email){
        initComponents();
        this.parent = parent;
        this.cardLayout = cardLayout; 
        setText(email);
        tenDNTextField.setEditable(false);
        motaTextField.setEditable(false);
        tenBank.setEditable(false);
        stkTextField.setEditable(false);
        nameTextField.setEditable(false);
        
        passTextField.setEditable(false);
        passconfirmTextField.setEditable(false);
    }
    public KHACHSAN getData(){
        String name = tenDNTextField.getText();
        String mota = motaTextField.getText();
        String bank = (String) tenBank.getSelectedItem();
        String stk = stkTextField.getText();
                
        return new KHACHSAN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        tenDNTextField = new javax.swing.JTextField();
        bankLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        changeBtn = new javax.swing.JButton();
        inforLabel = new javax.swing.JLabel();
        passLabel1 = new javax.swing.JLabel();
        commitBtn1 = new javax.swing.JButton();
        stkLabel = new javax.swing.JLabel();
        dateLabel2 = new javax.swing.JLabel();
        stkTextField = new javax.swing.JTextField();
        motaTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        tenBank = new javax.swing.JComboBox<>();
        passTextField = new javax.swing.JPasswordField();
        passconfirmTextField = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(1400, 1200));
        setPreferredSize(new java.awt.Dimension(1320, 1025));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));

        emailLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email");
        emailLabel.setToolTipText("");

        emailTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        NameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("Tên Khách Sạn");

        tenDNTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        tenDNTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        tenDNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenDNTextFieldActionPerformed(evt);
            }
        });

        bankLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        bankLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankLabel.setText("Tên Ngân Hàng");

        passLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel.setText("Xác nhận mật khẩu");

        changeBtn.setBackground(new java.awt.Color(0, 102, 102));
        changeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setText("Chỉnh Sửa");
        changeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        inforLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        inforLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inforLabel.setText("Hồ Sơ Của Tôi");

        passLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        passLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel1.setText("Mật khẩu");

        commitBtn1.setBackground(new java.awt.Color(0, 102, 102));
        commitBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        commitBtn1.setForeground(new java.awt.Color(255, 255, 255));
        commitBtn1.setText("Lưu");
        commitBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        commitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitBtn1ActionPerformed(evt);
            }
        });

        stkLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        stkLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stkLabel.setText("Số Tài Khoản");

        dateLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        dateLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel2.setText("Mô tả");

        stkTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        motaTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Họ và Tên");

        nameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nameTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        tenBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABBANK", "ACB", "ANZ VL", "Agribank", "BAOVIET Bank", "Bac A Bank", "BVBank", "BIDV", "CIMB", "Co-opBank", "DongA Bank", "Eximbank", "GPBank", "HLB VN", "HDBank", "HSBC", "IVB", "KienlongBank", "LienVietPostBank", "MB Bank", "MBV", "MSB", "Nam A Bank", "NCB", "OCB", "PBVN", "PGBank", "PVcomBank", "Sacombank", "SAIGONBANK", "SCB", "SCB VL", "SeABank", "SHB", "SHB VN", "Techcombank", "TPBank", "UOB", "VDB", "VCB Neo", "VIB", "VietABank", "VietCapitalBank", "Vietcombank", "VietinBank", "Vietbank", "VPBank", "VRB", "Woori Bank", "VBSP" }));

        passTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        passconfirmTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(inforLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(commitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bankLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(stkLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(motaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(stkTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenDNTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenBank, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passconfirmTextField))
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inforLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenDNTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(passconfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenDNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenDNTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenDNTextFieldActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        tenDNTextField.setEditable(true);
        motaTextField.setEditable(true);
        tenBank.setEditable(true);
        stkTextField.setEditable(true);
        nameTextField.setEditable(true);
        passTextField.setEditable(true);
        passconfirmTextField.setEditable(true);
    }//GEN-LAST:event_changeBtnActionPerformed

    private void commitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitBtn1ActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText();
        String tendn = tenDNTextField.getText();
        String mota = motaTextField.getText();
        String bank = (String) tenBank.getSelectedItem();
        String stk = stkTextField.getText();
        
        String password = passTextField.getText();
        String passwordcf = passconfirmTextField.getText(); // nếu bạn muốn cập nhật mật khẩu

        if (tendn.isEmpty() || mota.isEmpty() || stk.isEmpty() || bank.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!password.isEmpty()) {
            if (!password.equals(passwordcf)) {
                JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                ks.setMATKHAU(password); // cập nhật mật khẩu mới
            }
        }
        
        //gán tt    
        ks.setTENDN(tendn);
        ks.setMOTA(mota);
        ks.setBANK(bank);
        ks.setSTK(stk);
        ks.setHOTEN(name);
        
        System.out.println("\n");
        System.out.println(ks.getTENDN());
        System.out.println(ks.getMOTA());
        System.out.println(ks.getBANK());
        System.out.println(ks.getSTK());
        System.out.println(ks.getHOTEN());
        System.out.println(ks.getMATKHAU());
        
        // cập nhật
        KhachSan_DAO dao = new KhachSan_DAO();
        dao.update(ks);
        
        tenDNTextField.setEditable(false);
        motaTextField.setEditable(false);
        tenBank.setEditable(false);
        stkTextField.setEditable(false);
        nameTextField.setEditable(false);
        passTextField.setEditable(false);
        passconfirmTextField.setEditable(false);
    }//GEN-LAST:event_commitBtn1ActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JButton changeBtn;
    private javax.swing.JButton commitBtn1;
    private javax.swing.JLabel dateLabel2;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTextField;
    private javax.swing.JLabel inforLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField motaTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JPasswordField passconfirmTextField;
    private javax.swing.JLabel stkLabel;
    private javax.swing.JTextField stkTextField;
    private javax.swing.JComboBox<String> tenBank;
    private javax.swing.JTextField tenDNTextField;
    // End of variables declaration//GEN-END:variables
}
