package GUI.Component;
import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import org.knowm.xchart.*;
import org.knowm.xchart.style.Styler;

/**
 *
 * @author Admin
 */
public class DashBoard extends javax.swing.JPanel {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        
        // layout lưới 2×2 với khoảng cách 5px
        setLayout(new GridLayout(2, 2, 5, 5));

        // Chart 1: Bar chart
        CategoryChart barChart = new CategoryChartBuilder()
            .width(0).height(0)  // size tính tự động theo panel
            .title("Doanh thu Q1")
            .xAxisTitle("Tháng")
            .yAxisTitle("Triệu VND")
            .build();
        barChart.addSeries("Doanh thu",
            Arrays.asList("Th01","Th02","Th03"),
            Arrays.asList(120, 150, 180)
        );
        add(new XChartPanel<>(barChart));

        // Chart 2: Pie chart
        PieChart pieChart = new PieChartBuilder().title("Tỷ lệ SP").build();
        pieChart.addSeries("SP A", 40);
        pieChart.addSeries("SP B", 30);
        pieChart.addSeries("SP C", 30);
        add(new XChartPanel<>(pieChart));

        // Chart 3: Line chart
        XYChart lineChart = new XYChartBuilder()
            .title("Giá theo ngày")
            .xAxisTitle("Ngày")
            .yAxisTitle("Giá")
            .build();
        lineChart.addSeries("Cổ phiếu",
            new double[]{1,2,3,4,5},
            new double[]{10,12,11,14,13}
        );
        add(new XChartPanel<>(lineChart));

        // Chart 4: Histogram
        Histogram hist = new Histogram(
            Arrays.asList(1,2,2,3,3,3,4,4,5), 5);
        CategoryChart histChart = new CategoryChartBuilder()
            .title("Phân bố")
            .xAxisTitle("Giá trị")
            .yAxisTitle("Tần suất")
            .build();
        histChart.addSeries("Tần suất",
            hist.getxAxisData(), hist.getyAxisData()
        );
        add(new XChartPanel<>(histChart));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
