package GUI.Component;

/**
 *
 * @author Admin
 */
import java.util.Hashtable;
import java.lang.reflect.Field;
import javax.swing.*;
import model.Phong_KS;
import java.lang.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class formKS extends javax.swing.JPanel {

    /**
     * Creates new form formKS
     */
    public formKS() {
        initComponents();
    }
    
    public void resetFields() {
        txtGia.setText("");
        txtLoaiPhong.setText("");
        txtMota.setText("");
        txtSoLuong.setText("");
        txtSoLuongConLai.setText("");
    }
    public Phong_KS getData(Integer ID_KS){
        Integer ID = 1;
        String loaiPhong = txtLoaiPhong.getText();
        Long soLuong = Long.valueOf(txtSoLuong.getText());
        Long soLuongConLai = Long.valueOf(txtSoLuongConLai.getText());
        Long gia = Long.valueOf(txtGia.getText());
        String moTa = txtMota.getText();
        LocalDate today = LocalDate.now();
        
        return new Phong_KS(ID, ID_KS , loaiPhong, 
                moTa, gia, soLuong, soLuongConLai, today);
    }
    
    public void setData(Object... args) {
    // Tập hợp tất cả các thành phần cần gán dữ liệu
    JComponent[] components = new JComponent[] {
        txtLoaiPhong, txtSoLuong,
        txtSoLuongConLai, txtGia, txtMota // txtMoTa là JTextArea
    };

    int len = Math.min(args.length, components.length);

    for (int i = 0; i < len; i++) {
        String value = (args[i] != null) ? String.valueOf(args[i]) : "";

        if (components[i] instanceof JTextField) {
            ((JTextField) components[i]).setText(value);
        } else if (components[i] instanceof JTextArea) {
            ((JTextArea) components[i]).setText(value);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoLuong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoLuongConLai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(819, 340));
        setLayout(null);

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        add(txtSoLuong);
        txtSoLuong.setBounds(130, 80, 170, 20);

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });
        add(txtGia);
        txtGia.setBounds(620, 20, 170, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Loại Phòng");
        add(jLabel3);
        jLabel3.setBounds(10, 20, 108, 22);

        txtLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiPhongActionPerformed(evt);
            }
        });
        add(txtLoaiPhong);
        txtLoaiPhong.setBounds(130, 20, 170, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Số lượng");
        add(jLabel4);
        jLabel4.setBounds(10, 80, 108, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Giá");
        add(jLabel2);
        jLabel2.setBounds(450, 20, 132, 22);

        txtSoLuongConLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongConLaiActionPerformed(evt);
            }
        });
        add(txtSoLuongConLai);
        txtSoLuongConLai.setBounds(620, 80, 170, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Số lượng còn lại");
        add(jLabel8);
        jLabel8.setBounds(450, 80, 132, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Mô tả");
        add(jLabel9);
        jLabel9.setBounds(140, 190, 61, 25);

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane1.setViewportView(txtMota);

        add(jScrollPane1);
        jScrollPane1.setBounds(250, 160, 350, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiPhongActionPerformed

    private void txtSoLuongConLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongConLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongConLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongConLai;
    // End of variables declaration//GEN-END:variables
}
