package GUI.Component;

/**
 *
 * @author Admin
 */
import java.util.Hashtable;
import java.lang.reflect.Field;
import javax.swing.*;
import model.Phong_KS;
import java.lang.*;

public class formKS extends javax.swing.JPanel {

    /**
     * Creates new form formKS
     */
    public formKS() {
        initComponents();
    }
    
    public Phong_KS getData(){
        Integer ID = Integer.valueOf(txtID.getText());
        Integer ID_Dn = Integer.valueOf("11");
        String tenPhong = txtTenPhong.getText();
        String loaiPhong = txtLoaiPhong.getText();
        Long soLuong = Long.valueOf(txtSoLuong.getText());
        Long soLuongConLai = Long.valueOf(txtSoLuongConLai.getText());
        Long gia = Long.valueOf(txtGia.getText());
        String moTa = txtMota.getText();
        
        return new Phong_KS(ID, ID_Dn, tenPhong, loaiPhong, gia, 
                moTa, soLuong, soLuongConLai);
    }
    
    public void setData(Object... args) {
    // Tập hợp tất cả các thành phần cần gán dữ liệu
    JComponent[] components = new JComponent[] {
        txtID, txtTenPhong, txtLoaiPhong, txtSoLuong,
        txtSoLuongConLai, txtGia, txtMota // txtMoTa là JTextArea
    };

    int len = Math.min(args.length, components.length);

    for (int i = 0; i < len; i++) {
        String value = (args[i] != null) ? String.valueOf(args[i]) : "";

        if (components[i] instanceof JTextField) {
            ((JTextField) components[i]).setText(value);
        } else if (components[i] instanceof JTextArea) {
            ((JTextArea) components[i]).setText(value);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenPhong = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtSoLuongConLai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(819, 340));
        setLayout(null);

        txtTenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPhongActionPerformed(evt);
            }
        });
        add(txtTenPhong);
        txtTenPhong.setBounds(620, 20, 169, 22);

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        add(txtSoLuong);
        txtSoLuong.setBounds(130, 140, 169, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Tên Phòng");
        add(jLabel1);
        jLabel1.setBounds(450, 20, 132, 22);

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });
        add(txtGia);
        txtGia.setBounds(620, 80, 169, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Loại Phòng");
        add(jLabel3);
        jLabel3.setBounds(6, 80, 108, 22);

        txtLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiPhongActionPerformed(evt);
            }
        });
        add(txtLoaiPhong);
        txtLoaiPhong.setBounds(132, 82, 169, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Số lương");
        add(jLabel4);
        jLabel4.setBounds(10, 140, 108, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Giá");
        add(jLabel2);
        jLabel2.setBounds(450, 80, 132, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("ID");
        add(jLabel7);
        jLabel7.setBounds(6, 22, 108, 22);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID);
        txtID.setBounds(132, 24, 169, 22);

        txtSoLuongConLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongConLaiActionPerformed(evt);
            }
        });
        add(txtSoLuongConLai);
        txtSoLuongConLai.setBounds(620, 140, 169, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Số lượng còn lại");
        add(jLabel8);
        jLabel8.setBounds(450, 140, 132, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Mô tả");
        add(jLabel9);
        jLabel9.setBounds(140, 250, 61, 25);

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane1.setViewportView(txtMota);

        add(jScrollPane1);
        jScrollPane1.setBounds(250, 220, 350, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPhongActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiPhongActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtSoLuongConLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongConLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongConLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongConLai;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
}
