package GUI.Component;

/**
 *
 * @author Admin
 */
import java.util.Hashtable;
import java.lang.reflect.Field;
import javax.swing.*;
import MODEL.Chuyen_DangTai;
import java.lang.*;

public class formPT extends javax.swing.JPanel {

    /**
     * Creates new form formKS
     */
    public formPT() {
        initComponents();
    }
    
    public Chuyen_DangTai getData() {
        Integer id = Integer.valueOf(txtID.getText());
        Integer doanhNghiepId = 12; // Tạm thời fix cứng hoặc truyền vào sau
        String loaiPT = txtLoaiPT.getText();
        String diemDi = txtDiemDi.getText();
        String diemDen = txtDiemDen.getText();
        String ngayGioKhoiHanh = txtThoiGian.getText();
        Long gia = Long.valueOf(txtGia.getText());
        String moTa = txtMoTa.getText();
        Long soLuongConLai = Long.valueOf(txtSoLuongConLai.getText());
        Long tongSoLuong = Long.valueOf(txtTongSoLuong.getText());

        return new Chuyen_DangTai(id, doanhNghiepId, loaiPT, diemDi, diemDen, ngayGioKhoiHanh, gia, moTa, soLuongConLai, tongSoLuong);
    }

    public void setData(Object... args) {
        JComponent[] components = new JComponent[] {
            txtID, txtLoaiPT, txtDiemDi, txtDiemDen, txtThoiGian, txtGia, txtMoTa, txtSoLuongConLai, txtTongSoLuong
        };

        int len = Math.min(args.length, components.length);
        for (int i = 0; i < len; i++) {
            String value = (args[i] != null) ? String.valueOf(args[i]) : "";
            if (components[i] instanceof JTextField) {
                ((JTextField) components[i]).setText(value);
            } else if (components[i] instanceof JTextArea) {
                ((JTextArea) components[i]).setText(value);
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoaiPT = new javax.swing.JTextField();
        txtTongSoLuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiemDi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtSoLuongConLai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        txtDiemDen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(785, 340));
        setLayout(null);

        txtLoaiPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiPTActionPerformed(evt);
            }
        });
        add(txtLoaiPT);
        txtLoaiPT.setBounds(620, 20, 169, 22);

        txtTongSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSoLuongActionPerformed(evt);
            }
        });
        add(txtTongSoLuong);
        txtTongSoLuong.setBounds(130, 170, 169, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Loại phương tiện");
        add(jLabel1);
        jLabel1.setBounds(450, 20, 140, 22);

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });
        add(txtGia);
        txtGia.setBounds(620, 80, 169, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Điểm đi");
        add(jLabel3);
        jLabel3.setBounds(10, 70, 108, 22);

        txtDiemDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemDiActionPerformed(evt);
            }
        });
        add(txtDiemDi);
        txtDiemDi.setBounds(130, 70, 169, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Số lương");
        add(jLabel4);
        jLabel4.setBounds(10, 170, 108, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Giá");
        add(jLabel2);
        jLabel2.setBounds(450, 80, 132, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("ID");
        add(jLabel7);
        jLabel7.setBounds(10, 20, 108, 30);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID);
        txtID.setBounds(130, 20, 170, 22);

        txtSoLuongConLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongConLaiActionPerformed(evt);
            }
        });
        add(txtSoLuongConLai);
        txtSoLuongConLai.setBounds(620, 170, 169, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Số lượng còn lại");
        add(jLabel8);
        jLabel8.setBounds(450, 170, 132, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Mô tả");
        add(jLabel9);
        jLabel9.setBounds(140, 250, 61, 25);

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane1.setViewportView(txtMota);

        add(jScrollPane1);
        jScrollPane1.setBounds(250, 220, 350, 80);

        txtDiemDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemDenActionPerformed(evt);
            }
        });
        add(txtDiemDen);
        txtDiemDen.setBounds(130, 120, 169, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Điểm đến");
        add(jLabel5);
        jLabel5.setBounds(10, 120, 108, 30);

        txtThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianActionPerformed(evt);
            }
        });
        add(txtThoiGian);
        txtThoiGian.setBounds(620, 130, 169, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Ngày khởi hành");
        add(jLabel10);
        jLabel10.setBounds(450, 130, 132, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoaiPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiPTActionPerformed

    private void txtTongSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongSoLuongActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtSoLuongConLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongConLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongConLaiActionPerformed

    private void txtDiemDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemDiActionPerformed

    private void txtDiemDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemDenActionPerformed

    private void txtThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiGianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDiemDen;
    private javax.swing.JTextField txtDiemDi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLoaiPT;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSoLuongConLai;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTongSoLuong;
    // End of variables declaration//GEN-END:variables
}
