package GUI.Component;

import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;

import model.PhongCard;
import GUI.Component.HotelCard;
import MODEL.NGUOIDUNG;
import DAO.PhongKS_DAO;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import model.Phong_KS;
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form HomePage2
     */
    private NGUOIDUNG user;
    private PhongKS_DAO phongKSDao = new PhongKS_DAO();
    public HomePage(NGUOIDUNG user){
        this.user = user;
        initComponents();
        loadData();
    }
    
    public void loadData(){
        listCard.setLayout(new BoxLayout(listCard, BoxLayout.Y_AXIS));
        jScrollPane1.setBorder(null);
        add(jScrollPane1, BorderLayout.CENTER);

        // panel chứa các card
        listCard.setBackground(Color.WHITE);
        jScrollPane1.setViewportView(listCard);
        
        Vector<Phong_KS> listPhongKS = phongKSDao.showOnCard();
        int gap=10;
        for(Phong_KS phong : listPhongKS){
            HotelCard card = new HotelCard(phong, user);
            listCard.add(card);
            listCard.add(Box.createVerticalStrut(gap));
        }
        int cardH = listCard.getComponent(0).getPreferredSize().height;
        int totalH = listPhongKS.size() * cardH + (listPhongKS.size() - 1) * gap;
        // chiều rộng bất kỳ (BoxLayout sẽ stretch full)
        listCard.setPreferredSize(new Dimension(0, totalH));
        // 5. Nhanh hơn cuộn dọc
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        
        
    }
    
    public List<PhongCard> fakeData() throws SQLException{
        List<PhongCard> cards = new ArrayList<>();
        String imagePath = "/image/phongKS.png";
        String[] tags = { "Bãi biển", "Miễn phí Wi-Fi", "Hồ bơi" };
        for (int i = 1; i <= 12; i++) {
            cards.add(new PhongCard(
                imagePath,
                "Phòng #" + i,
                4,
                "Địa điểm " + i,
                "Một lựa chọn tuyệt vời cho kỳ nghỉ.",
                8.6, 120 + i, 800000 + i*1000.0
            ));
        }
        return cards;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1320, 1025));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1320, 100000));

        listCard.setPreferredSize(new java.awt.Dimension(1000, 1025));

        javax.swing.GroupLayout listCardLayout = new javax.swing.GroupLayout(listCard);
        listCard.setLayout(listCardLayout);
        listCardLayout.setHorizontalGroup(
            listCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1308, Short.MAX_VALUE)
        );
        listCardLayout.setVerticalGroup(
            listCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listCard);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listCard;
    // End of variables declaration//GEN-END:variables
}
