package GUI.Component;

/**
 *
 * @author Admin
 */
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;

import model.PhongCard;

public class HotelCard extends javax.swing.JPanel {

    /**
     * Creates new form HotelCard2
     */
    public HotelCard() {
        initComponents();
    }
    
    public HotelCard(PhongCard data){
        initComponents();
        customImg(data);
        customContent(data);
    }
    
    public JPanel getCard(){
        return this;
    };
    
    public void customImg(PhongCard data){
        // ----- LEFT: ảnh lớn -----
        String imagePath = data.getImagePath();
        ImageIcon raw = new ImageIcon(getClass().getResource(imagePath));
        Image scaled = raw.getImage()
            .getScaledInstance(370, 290, Image.SCALE_SMOOTH);
        
        image.setIcon(new ImageIcon(scaled));
        image.setBorder(new LineBorder(Color.LIGHT_GRAY,1,true));
    }
    
    public void customContent(PhongCard data){
        //Title
        txtTitle.setText(data.getLoaiPhong());
        
        
        //Star
        numStar.setLayout(new FlowLayout(FlowLayout.LEFT, 2, 0));
        for (int i = 1; i <= data.getStart(); i++) {
            String path = "/image/star.png";
            numStar.add(new JLabel(new ImageIcon(getClass().getResource(path))));
        }
        
        //Location
        txtLocation.setText("<html><font color='#007BFF'><u>" + data.getLocation() + "</u></font></html>");
        
        
        //Desc
        txtDescription.setText("<html><i>\"" + data.getDescription() + "\"</i></html>");
        txtDescription.setForeground(Color.DARK_GRAY);
        
        //Right Pannel
        String desc_score = data.getScore() >= 9 ? "Xuất sắc" : data.getScore() >= 8 ? "Tuyệt vời" : "Rất tốt";
        txtScore.setText(desc_score);
        
        txtReviews.setText(data.getReviews() + " Reviews");
        
        txtPrice.setText(String.valueOf(data.getPrice()));
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        numStar = new javax.swing.JPanel();
        txtLocation = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        rightPanl = new javax.swing.JPanel();
        btnDetail = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        txtScore = new javax.swing.JLabel();
        txtReviews = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        setPreferredSize(new java.awt.Dimension(1000, 320));

        image.setText("jLabel1");
        image.setPreferredSize(new java.awt.Dimension(370, 290));

        content.setPreferredSize(new java.awt.Dimension(350, 290));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitle.setText("Khách sạn Sunires");
        txtTitle.setToolTipText("");
        txtTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout numStarLayout = new javax.swing.GroupLayout(numStar);
        numStar.setLayout(numStarLayout);
        numStarLayout.setHorizontalGroup(
            numStarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        numStarLayout.setVerticalGroup(
            numStarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtLocation.setText("Địa điểm");

        txtDescription.setText("Mô tả");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(numStar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDetail.setText("Xem chi tiết");

        btnBooking.setText("Đặt");

        txtScore.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtScore.setText("Score");

        txtReviews.setText("Số lượt reviews");

        txtPrice.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrice.setText("4000000");
        txtPrice.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtPrice.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout rightPanlLayout = new javax.swing.GroupLayout(rightPanl);
        rightPanl.setLayout(rightPanlLayout);
        rightPanlLayout.setHorizontalGroup(
            rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanlLayout.createSequentialGroup()
                .addGroup(rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReviews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21))))
                    .addGroup(rightPanlLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rightPanlLayout.setVerticalGroup(
            rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReviews)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(rightPanl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rightPanl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnDetail;
    private javax.swing.JPanel content;
    private javax.swing.JLabel image;
    private javax.swing.JPanel numStar;
    private javax.swing.JPanel rightPanl;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JLabel txtLocation;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtReviews;
    private javax.swing.JLabel txtScore;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
