package GUI.Component;

/**
 *
 * @author Admin
 */
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.sql.*;

import MODEL.PhongCard;
import GUI.JFRAME.DatPhong;
import MODEL.NGUOIDUNG;
import java.util.logging.Level;
import java.util.logging.Logger;
import MODEL.Phong_KS;

public class HotelCard extends javax.swing.JPanel {

    /**
     * Creates new form HotelCard2
     */
    private NGUOIDUNG user;
    private Phong_KS phong;
    public HotelCard() {
        initComponents();
    }
    
    public HotelCard(Phong_KS phong, NGUOIDUNG user){
        this.phong = phong;
        this.user = user;
        initComponents();
        customImg(phong);
        customContent(phong);
    }
    
    public JPanel getCard(){
        return this;
    };
    
    public void customImg(Phong_KS data){
        // ----- LEFT: ảnh lớn -----
        Blob[] images = data.getImages();
        for (int i = 0; i < 3; i++) {
            if (images[i] != null) {
                byte[] imageData;
                try {
                    imageData = images[i].getBytes(1, (int) images[i].length());
                    BufferedImage img;
                    try {
                        img = ImageIO.read(new ByteArrayInputStream(imageData));
                        ImageIcon icon = new ImageIcon(
                            img.getScaledInstance(370, 290, Image.SCALE_SMOOTH));
                        image.setIcon(icon);
                        image.setBorder(new LineBorder(Color.LIGHT_GRAY,1,true));
                    } catch (IOException ex) {
                        Logger.getLogger(HotelCard.class.getName()).log(Level.SEVERE, null, ex);
                    }                 
                    return;
                } catch (SQLException ex) {
                    Logger.getLogger(HotelCard.class.getName()).log(Level.SEVERE, null, ex);
                }   
            } else {
                image.setIcon(null);
                image.setText("Không có ảnh");
                image.setBorder(new LineBorder(Color.LIGHT_GRAY,1,true));
            }
        }
    }
    
    public void customContent(Phong_KS data){
        //Title
        txtTitle.setText(data.getLoaiPhong());
        
        tenKSLabel.setText(data.getTenKS());
        
        //Star
        numStar.setLayout(new FlowLayout(FlowLayout.LEFT, 2, 0));
        for (int i = 1; i <= data.getStar(); i++) {
            String path = "/image/star.png";
            numStar.add(new JLabel(new ImageIcon(getClass().getResource(path))));
        }
        
        //Location
        txtLocation.setText("<html><font color='#007BFF'><u>" + data.getLocation() + "</u></font></html>");
        
        //Desc
        txtDescription.setText("<html><i>\"" + data.getMoTa()+ "\"</i></html>");
        txtDescription.setForeground(Color.DARK_GRAY);
        
        //Right Pannel
        String desc_score = data.getStar() >= 4 ? "Xuất sắc" : data.getStar() >= 3 ? "Trung bình" : "Tệ";
        txtScore.setText(desc_score);
        
        txtReviews.setText(data.getNumReviews()+ " Reviews");
        
        txtPrice.setText(String.valueOf(data.getGia()));
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        numStar = new javax.swing.JPanel();
        txtLocation = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        tenKSLabel = new javax.swing.JLabel();
        rightPanl = new javax.swing.JPanel();
        btnDetail = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        txtScore = new javax.swing.JLabel();
        txtReviews = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        setPreferredSize(new java.awt.Dimension(1000, 320));

        image.setText("jLabel1");
        image.setPreferredSize(new java.awt.Dimension(370, 290));

        content.setPreferredSize(new java.awt.Dimension(350, 290));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitle.setText("Khách sạn Sunires");
        txtTitle.setToolTipText("");
        txtTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout numStarLayout = new javax.swing.GroupLayout(numStar);
        numStar.setLayout(numStarLayout);
        numStarLayout.setHorizontalGroup(
            numStarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        numStarLayout.setVerticalGroup(
            numStarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtLocation.setText("Địa điểm");

        txtDescription.setText("Mô tả");

        tenKSLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(numStar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(tenKSLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(tenKSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDetail.setText("Xem chi tiết");

        btnBooking.setText("Đặt");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        txtScore.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtScore.setText("Score");

        txtReviews.setText("Số lượt reviews");

        txtPrice.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrice.setText("4000000");
        txtPrice.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtPrice.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout rightPanlLayout = new javax.swing.GroupLayout(rightPanl);
        rightPanl.setLayout(rightPanlLayout);
        rightPanlLayout.setHorizontalGroup(
            rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanlLayout.createSequentialGroup()
                .addGroup(rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReviews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21))))
                    .addGroup(rightPanlLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rightPanlLayout.setVerticalGroup(
            rightPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReviews)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(rightPanl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rightPanl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        DatPhong datPhongFrame = new DatPhong(this.user, this.phong);
        datPhongFrame.pack();                        // hoặc setSize(...)
        datPhongFrame.setLocationRelativeTo(null);   // canh giữa màn hình
        datPhongFrame.setVisible(true);
    }//GEN-LAST:event_btnBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnDetail;
    private javax.swing.JPanel content;
    private javax.swing.JLabel image;
    private javax.swing.JPanel numStar;
    private javax.swing.JPanel rightPanl;
    private javax.swing.JLabel tenKSLabel;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JLabel txtLocation;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtReviews;
    private javax.swing.JLabel txtScore;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
