package GUI.Component;

import DAO.Login_SignUp_Check;
import GUI.JFRAME.Menu_KhachHang;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import GUI.JFRAME.Menu_KhachSan;
import MODEL.NGUOIDUNG;

public class LoginPanel extends javax.swing.JPanel {

    private JPanel parent;
    private CardLayout cardLayout;
    
    public LoginPanel() {
        initComponents();
    }

    public LoginPanel(JPanel parent, CardLayout cardLayout) {
        initComponents();
        this.parent = parent;
        this.cardLayout = cardLayout;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Green_Panel = new javax.swing.JPanel();
        White_Panel = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Dien_username = new javax.swing.JTextField();
        Login = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Dien_password = new javax.swing.JPasswordField();
        Forgotten_password = new javax.swing.JButton();
        confirm_login = new javax.swing.JButton();
        Label_ChangeTo_SignUp = new javax.swing.JLabel();
        Change_to_signup = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1300, 750));

        Green_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Green_Panel.setPreferredSize(new java.awt.Dimension(650, 750));

        javax.swing.GroupLayout Green_PanelLayout = new javax.swing.GroupLayout(Green_Panel);
        Green_Panel.setLayout(Green_PanelLayout);
        Green_PanelLayout.setHorizontalGroup(
            Green_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        Green_PanelLayout.setVerticalGroup(
            Green_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        White_Panel.setBackground(new java.awt.Color(244, 244, 242));
        White_Panel.setPreferredSize(new java.awt.Dimension(650, 750));

        Username.setBackground(new java.awt.Color(0, 0, 0));
        Username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setText("Email:");

        Dien_username.setBackground(new java.awt.Color(249, 249, 249));
        Dien_username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Dien_username.setForeground(new java.awt.Color(102, 102, 102));
        Dien_username.setPreferredSize(new java.awt.Dimension(65, 30));

        Login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 102, 102));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("ĐĂNG NHẬP");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setText("Mật Khẩu:");

        Dien_password.setBackground(new java.awt.Color(249, 249, 249));
        Dien_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Dien_password.setForeground(new java.awt.Color(102, 102, 102));
        Dien_password.setPreferredSize(new java.awt.Dimension(65, 30));

        Forgotten_password.setBackground(new java.awt.Color(244, 244, 242));
        Forgotten_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Forgotten_password.setForeground(new java.awt.Color(102, 102, 102));
        Forgotten_password.setText("Quên mật khẩu?");
        Forgotten_password.setBorder(null);
        Forgotten_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forgotten_passwordActionPerformed(evt);
            }
        });

        confirm_login.setBackground(new java.awt.Color(0, 102, 102));
        confirm_login.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        confirm_login.setForeground(new java.awt.Color(255, 255, 255));
        confirm_login.setText("Đăng Nhập");
        confirm_login.setPreferredSize(new java.awt.Dimension(140, 35));
        confirm_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_loginActionPerformed(evt);
            }
        });

        Label_ChangeTo_SignUp.setForeground(new java.awt.Color(102, 102, 102));
        Label_ChangeTo_SignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ChangeTo_SignUp.setText("Tôi chưa có tài khoản");
        Label_ChangeTo_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Change_to_signup.setBackground(new java.awt.Color(244, 244, 242));
        Change_to_signup.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Change_to_signup.setForeground(new java.awt.Color(0, 102, 102));
        Change_to_signup.setText("Đăng Ký");
        Change_to_signup.setPreferredSize(new java.awt.Dimension(140, 35));
        Change_to_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change_to_signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout White_PanelLayout = new javax.swing.GroupLayout(White_Panel);
        White_Panel.setLayout(White_PanelLayout);
        White_PanelLayout.setHorizontalGroup(
            White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(White_PanelLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Forgotten_password)
                            .addComponent(Password)
                            .addComponent(Username)
                            .addComponent(Dien_username, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addComponent(Dien_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(White_PanelLayout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(Login))
                        .addGroup(White_PanelLayout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirm_login, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(Change_to_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_ChangeTo_SignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        White_PanelLayout.setVerticalGroup(
            White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(White_PanelLayout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(Login)
                    .addGap(40, 40, 40)
                    .addComponent(Username)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Dien_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(Password)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Dien_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Forgotten_password)
                    .addGap(43, 43, 43)
                    .addComponent(confirm_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(Label_ChangeTo_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Change_to_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(156, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Green_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(White_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Green_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(White_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void Forgotten_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forgotten_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Forgotten_passwordActionPerformed

    private void confirm_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_loginActionPerformed
        // TODO add your handling code here:
        
        // lấy thông tin tài khoản và mật khẩu người dùng nhập
        String email = Dien_username.getText(); // Dien_username là TextField cho username
        String password = new String(Dien_password.getPassword());
        // Dien_password là PasswordField cho mật khẩu
        String accountType = Login_SignUp_Check.checkLogin(email, password);
        
        if (accountType != null) {
            // Hiển thị menu tùy theo loại tài khoản
            // Chuyển hướng tới giao diện chính cho người dùng
            if (accountType.equals("KHACHHANG")){// NẾU LÀ KHÁCH HÀNG.
                
                Menu_KhachHang MenuFrame= new Menu_KhachHang(email);
                 //Menu_KhachHang MenuFrame= new Menu_KhachHang(name);
                MenuFrame.pack();
                MenuFrame.setLocationRelativeTo(null);
                MenuFrame.setVisible(true);
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(LoginPanel.this);
                currentFrame.dispose();
                
            } else if (accountType.equals("DOANHNGHIEP")){ // NẾU LÀ DOANH NGHIỆP.
                
                String bussinessTypeString = Login_SignUp_Check.checkLoaiDN(email, password);
                if (bussinessTypeString.equals("KHACHSAN")){
                    
                    NGUOIDUNG user = Login_SignUp_Check.getNguoiDung(email);
                    Menu_KhachSan MenuFrame = new Menu_KhachSan(user.getHOTEN());
                    MenuFrame.pack();
                    MenuFrame.setLocationRelativeTo(null);
                    MenuFrame.setVisible(true);
                    JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(LoginPanel.this);
                    currentFrame.dispose();
                } else if (bussinessTypeString.equals("HANGPHUONGTIEN")){
                    Menu_PhuongTien MenuFrame= new Menu_PhuongTien(username);
                    MenuFrame.pack();
                    MenuFrame.setLocationRelativeTo(null);
                    MenuFrame.setVisible(true);
                    JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(LoginPanel.this);
                    currentFrame.dispose();
                }
                
            }
        } else {
            //JOptionPane để hiện lên thông báo không đăng nhập thành công.
            //this là form hiện tại (làm cửa sổ cha).
            //"Đăng nhập thất bại!" là thông tin thông báo.
            //"Lỗi" là title của bảng thông báo.
            //JOptionPane.ERROR_MESSAGE để hiện lên icon dấu x đỏ cảnh báo.
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirm_loginActionPerformed

    private void Change_to_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_to_signupActionPerformed
        // TODO add your handling code here:
        cardLayout.show(parent, "register");
    }//GEN-LAST:event_Change_to_signupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change_to_signup;
    private javax.swing.JPasswordField Dien_password;
    private javax.swing.JTextField Dien_username;
    private javax.swing.JButton Forgotten_password;
    private javax.swing.JPanel Green_Panel;
    private javax.swing.JLabel Label_ChangeTo_SignUp;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel White_Panel;
    private javax.swing.JButton confirm_login;
    // End of variables declaration//GEN-END:variables
}
