package GUI.Component;

import MODEL.KHACHHANG;
import DAO.KhachHang_DAO;
import DAO.DonChinhSua_DAO;
import DAO.DonDat_DAO;
import MODEL.DonDat;
import MODEL.DonChinhSua;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import javax.swing.JOptionPane;  
import java.text.SimpleDateFormat;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author bobui
 */
public class quanlydatKhachHang extends javax.swing.JPanel {
    private JPanel parent;
    private CardLayout cardLayout;
    private KHACHHANG kh;
    /**
     * Creates new form quanlydatKhachHang
     */
    public quanlydatKhachHang(JPanel parent, CardLayout cardLayout,String email ) {
        KhachHang_DAO khdao = new KhachHang_DAO();
        this.kh = khdao.select(email);
        //System.out.print(kh.getID());
        //System.out.print(kh.getEMAIL());
        kh.setID(kh.getID());
        
        initComponents();
        loadtable();
        
        javax.swing.table.DefaultTableCellRenderer dateRenderer = new javax.swing.table.DefaultTableCellRenderer() {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            @Override
            protected void setValue(Object value) {
                if (value instanceof java.util.Date) {
                    setText(sdf.format((java.util.Date) value));
                } else {
                    setText((value != null) ? value.toString() : "");
                }
            }
        };

        // Gán renderer cho các cột có kiểu ngày
        jTable1.getColumnModel().getColumn(1).setCellRenderer(dateRenderer); // Ngày nhận
        jTable1.getColumnModel().getColumn(2).setCellRenderer(dateRenderer); // Ngày trả
        jTable1.getColumnModel().getColumn(5).setCellRenderer(dateRenderer); // Ngày đặt

        // Ví dụ: thêm dữ liệu mẫu
        // javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        // model.setRowCount(0); // Xóa dòng cũ

        // java.util.Date now = new java.util.Date();
        // model.addRow(new Object[] {101, now, now, 3, 450000.0, now});
        // model.addRow(new Object[] {102, now, now, 2, 300000.0, now});
    }
    
    

 
    
    public void loadtable(){
        DonDat_DAO dao = new DonDat_DAO();
        Vector<DonDat> list = dao.selectByIDKH(kh.getID());
        
//        System.out.println(kh.getID());
//        System.out.println(kh.getEMAIL());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear old rows

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        for (DonDat d : list) {
//            System.out.println("ID: " + d.getId());
//            System.out.println("ngaynhan: " + d.getNgayNhan());
//            System.out.println("ngaytra: " + d.getNgayTra());
//            System.out.println("SL: " + d.getSl());
//            System.out.println("gia: " + d.getGia());
//            System.out.println("dat: " + d.getNgayDat());
            model.addRow(new Object[]{
                d.getId(),
                d.getNgayNhan(),
                d.getNgayTra(),
                d.getSl(),
                d.getGia(),
                d.getNgayDat()
            });
        }

 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        xoaBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        findBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1320, 1025));

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Ngày nhận", "Ngày trả", "Số lượng", "Giá", "Ngày đặt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        xoaBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        xoaBtn.setText("Xoá");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        editBtn.setText("Chỉnh sửa");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Tìm theo mã đơn");

        findBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        findBtn.setText("Tìm");
        findBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 714, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(findBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        // TODO add your handling code here     
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn cần xoá!");
        return;
    }
    Integer maDon = (Integer) jTable1.getValueAt(selectedRow, 0);
    java.util.Date ngayNhan = (java.util.Date) jTable1.getValueAt(selectedRow, 1);

    
    java.util.Date now = new java.util.Date();
    long diffMillis = ngayNhan.getTime() - now.getTime();
    long oneDayMillis = 24 * 60 * 60 * 1000;

    if (diffMillis < oneDayMillis) {
        JOptionPane.showMessageDialog(this, "Không thể xoá đơn này vì ngày nhận phòng đã gần kề!");
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá đơn này?", "Xác nhận xoá", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    // Xoá
    boolean success = DonDat_DAO.delete(maDon);
    if (success) {
        JOptionPane.showMessageDialog(this, "Xoá đơn thành công!");
        loadtable(); // Tải lại bảng
    } else {
        JOptionPane.showMessageDialog(this, "Xoá thất bại, vui lòng thử lại!");
    }
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn cần chỉnh sửa!");
        return;
    }

    Integer maDon = (Integer) jTable1.getValueAt(selectedRow, 0);
    java.util.Date ngayNhanCu = (java.util.Date) jTable1.getValueAt(selectedRow, 1);
    java.util.Date ngayTraCu = (java.util.Date) jTable1.getValueAt(selectedRow, 2);
    Integer slCu = (Integer) jTable1.getValueAt(selectedRow, 3);

    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    String ngayNhanMoiStr = JOptionPane.showInputDialog(this, "Nhập ngày nhận mới (dd/MM/yyyy):", sdf.format(ngayNhanCu));
    String ngayTraMoiStr = JOptionPane.showInputDialog(this, "Nhập ngày trả mới (dd/MM/yyyy):", sdf.format(ngayTraCu));
    String slMoiStr = JOptionPane.showInputDialog(this, "Nhập số lượng mới:", slCu);

    if (ngayNhanMoiStr == null || ngayTraMoiStr == null || slMoiStr == null) return;

    try {
//        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.util.Date ngayNhanMoi = sdf.parse(ngayNhanMoiStr);
        java.util.Date ngayTraMoi = sdf.parse(ngayTraMoiStr);
        int slMoi = Integer.parseInt(slMoiStr);

        if (ngayNhanMoi.after(ngayTraMoi)) {
            JOptionPane.showMessageDialog(this, "Ngày trả phải sau ngày nhận!");
            return;
        }
        if (slMoi <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
            return;
        }

        java.sql.Date today = new java.sql.Date(System.currentTimeMillis());
        if (!ngayNhanMoi.after(today)) {
            JOptionPane.showMessageDialog(this, "Ngày nhận mới phải sau ngày hiện tại!");
            return;
        }

        DonChinhSua model = new DonChinhSua();
        model.setDatPhongId(maDon);
        model.setNgayNhanMoi(ngayNhanMoi);
        model.setNgayTraMoi(ngayTraMoi);
        model.setSlMoi(slMoi);
        model.setTrangThaiDuyet("CHỜ DUYỆT");
        model.setTrangThaiThanhToan("CHƯA THANH TOÁN");

        DonChinhSua_DAO dao = new DonChinhSua_DAO();
        dao.insertDonChinhSua(model);

        JOptionPane.showMessageDialog(this, "Gửi đơn chỉnh sửa thành công! Đơn đang chờ duyệt.");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Dữ liệu nhập không hợp lệ!");
    }
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:
        String text = idTextField.getText().trim();
        if (text.isEmpty()) {
            loadtable(); // Nếu không nhập gì, load lại toàn bộ
            return;
        }
        try {
            int maDon = Integer.parseInt(text);
            DonDat don = new DonDat_DAO().select(maDon);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); 
            if (don != null && don.getIdKH().equals(kh.getID())) {
                model.addRow(new Object[]{
                    don.getId(),
                    don.getNgayNhan(),
                    don.getNgayTra(),
                    don.getSl(),
                    don.getGia(),
                    don.getNgayDat()
                });
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy đơn phù hợp!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã đơn phải là số!");
        }
        
    }//GEN-LAST:event_findBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBtn;
    private javax.swing.JButton findBtn;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
