package GUI.Component;

import MODEL.NGUOIDUNG;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class RegisterPanel extends javax.swing.JPanel {

    private JPanel parent;
    private CardLayout cardLayout;
    private SignUpKhachHang signUpKhachHang;
    private SignUpKhachSan signUpKS;

    public RegisterPanel() {
        initComponents();
    }

    public RegisterPanel(JPanel parent, CardLayout cardLayout, SignUpKhachHang signUpKhachHang, SignUpKhachSan signUpKS) {
        this.parent = parent;
        this.cardLayout = cardLayout;
        this.signUpKhachHang=signUpKhachHang;
        this.signUpKS=signUpKS;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        White_Panel = new javax.swing.JPanel();
        SignUp = new javax.swing.JLabel();
        Full_Name = new javax.swing.JLabel();
        Full_Name_Fill = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Email_Fill = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Password_Fill = new javax.swing.JPasswordField();
        Confirm_Password = new javax.swing.JLabel();
        Confirm_Password_Fill = new javax.swing.JPasswordField();
        Choose_KH = new javax.swing.JButton();
        Choose_DN = new javax.swing.JButton();
        Label_OR = new javax.swing.JLabel();
        Have_An_Account = new javax.swing.JLabel();
        Login = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(650, 750));

        White_Panel.setBackground(new java.awt.Color(244, 244, 242));
        White_Panel.setPreferredSize(new java.awt.Dimension(650, 750));

        SignUp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SignUp.setForeground(new java.awt.Color(0, 102, 102));
        SignUp.setText("ĐĂNG KÝ");

        Full_Name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Full_Name.setForeground(new java.awt.Color(0, 0, 0));
        Full_Name.setText("Họ và Tên:");

        Full_Name_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Full_Name_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Full_Name_Fill.setForeground(new java.awt.Color(102, 102, 102));
        Full_Name_Fill.setPreferredSize(new java.awt.Dimension(65, 30));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setText("Email:");

        Email_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Email_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Email_Fill.setForeground(new java.awt.Color(102, 102, 102));
        Email_Fill.setPreferredSize(new java.awt.Dimension(65, 30));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setText("Mật Khẩu:");

        Password_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Password_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Password_Fill.setForeground(new java.awt.Color(102, 102, 102));
        Password_Fill.setPreferredSize(new java.awt.Dimension(65, 30));

        Confirm_Password.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Confirm_Password.setForeground(new java.awt.Color(0, 0, 0));
        Confirm_Password.setText("Xác Nhận Mật Khẩu Lần 2:");

        Confirm_Password_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Confirm_Password_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Confirm_Password_Fill.setForeground(new java.awt.Color(102, 102, 102));
        Confirm_Password_Fill.setPreferredSize(new java.awt.Dimension(65, 30));

        Choose_KH.setBackground(new java.awt.Color(0, 102, 102));
        Choose_KH.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Choose_KH.setForeground(new java.awt.Color(255, 255, 255));
        Choose_KH.setText("Khách Hàng");
        Choose_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_KHActionPerformed(evt);
            }
        });

        Choose_DN.setBackground(new java.awt.Color(0, 102, 102));
        Choose_DN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Choose_DN.setForeground(new java.awt.Color(255, 255, 255));
        Choose_DN.setText("Khách Sạn");
        Choose_DN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Choose_DN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_DNActionPerformed(evt);
            }
        });

        Label_OR.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Label_OR.setForeground(new java.awt.Color(0, 0, 0));
        Label_OR.setText("Hay");

        Have_An_Account.setForeground(new java.awt.Color(102, 102, 102));
        Have_An_Account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Have_An_Account.setText("Tôi đã có tài khoản");
        Have_An_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 102, 102));
        Login.setText("Đăng Nhập");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout White_PanelLayout = new javax.swing.GroupLayout(White_Panel);
        White_Panel.setLayout(White_PanelLayout);
        White_PanelLayout.setHorizontalGroup(
            White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(White_PanelLayout.createSequentialGroup()
                .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(White_PanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Choose_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_OR)
                        .addGap(18, 18, 18)
                        .addComponent(Choose_DN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(White_PanelLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(SignUp))
                    .addGroup(White_PanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Have_An_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(White_PanelLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Confirm_Password)
                        .addComponent(Password)
                        .addComponent(Email)
                        .addComponent(Full_Name)
                        .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Confirm_Password_Fill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Password_Fill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Email_Fill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Full_Name_Fill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        White_PanelLayout.setVerticalGroup(
            White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, White_PanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(SignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Choose_DN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Choose_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_OR)))
                .addGap(18, 18, 18)
                .addComponent(Have_An_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(White_PanelLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(Full_Name)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Full_Name_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Email)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Email_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Password)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Password_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Confirm_Password)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Confirm_Password_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(White_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(White_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Choose_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_KHActionPerformed
        // TODO add your handling code here:
        
        // lấy thông tin người đăng ký nhập
        String fullname = Full_Name_Fill.getText(); // Email_Fill là TextField cho username
        String username = Email_Fill.getText(); // Email_Fill là TextField cho username
        String password = new String(Password_Fill.getPassword()); // Password_Fill là PasswordField cho mật khẩu
        String confirm_password = new String(Confirm_Password_Fill.getPassword()); // Password_Fill là PasswordField cho mật khẩu
        
        if(fullname.isEmpty() || username.isEmpty() || password.isEmpty() || confirm_password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn phải điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(!password.equals(confirm_password)){
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        NGUOIDUNG nguoidung=new NGUOIDUNG(username, password, fullname);
        signUpKhachHang.SetThongTin(nguoidung);
        
        cardLayout.show(parent, "SUKH");

    }//GEN-LAST:event_Choose_KHActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
         cardLayout.show(parent, "login");
    }//GEN-LAST:event_LoginActionPerformed

    private void Choose_DNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_DNActionPerformed
        // TODO add your handling code here:

        // lấy thông tin người đăng ký nhập
        String fullname = Full_Name_Fill.getText(); // Email_Fill là TextField cho username
        String username = Email_Fill.getText(); // Email_Fill là TextField cho username
        String password = new String(Password_Fill.getPassword()); // Password_Fill là PasswordField cho mật khẩu
        String confirm_password = new String(Confirm_Password_Fill.getPassword()); // Password_Fill là PasswordField cho mật khẩu

        if(fullname.isEmpty() || username.isEmpty() || password.isEmpty() || confirm_password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn phải điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(!password.equals(confirm_password)){
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        NGUOIDUNG nguoidung=new NGUOIDUNG(username, password, fullname);
        signUpKS.SetThongTin(nguoidung);

        cardLayout.show(parent, "SUKS");

    }//GEN-LAST:event_Choose_DNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choose_DN;
    private javax.swing.JButton Choose_KH;
    private javax.swing.JLabel Confirm_Password;
    private javax.swing.JPasswordField Confirm_Password_Fill;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Email_Fill;
    private javax.swing.JLabel Full_Name;
    private javax.swing.JTextField Full_Name_Fill;
    private javax.swing.JLabel Have_An_Account;
    private javax.swing.JLabel Label_OR;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Password_Fill;
    private javax.swing.JLabel SignUp;
    private javax.swing.JPanel White_Panel;
    // End of variables declaration//GEN-END:variables
}
