package GUI.Component;

import DAO.Login_SignUp_Check;
import MODEL.KHACHSAN;
import MODEL.NGUOIDUNG;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class SignUpKhachSan extends javax.swing.JPanel {
    
    private JPanel parent;
    private CardLayout cardLayout;
    KHACHSAN khachsan;

    public SignUpKhachSan() {
        initComponents();
    }

    public SignUpKhachSan(JPanel parent, CardLayout cardLayout) {
        initComponents();
        this.parent = parent;
        this.cardLayout = cardLayout;
    }
    
    public void SetThongTin(NGUOIDUNG nguoidung){
        this.khachsan=new KHACHSAN(nguoidung);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        White_Panel = new javax.swing.JPanel();
        Label_Information_Fill = new javax.swing.JLabel();
        Business_Name = new javax.swing.JLabel();
        Business_Name_Fill = new javax.swing.JTextField();
        Label_Address = new javax.swing.JLabel();
        Address_Fill = new javax.swing.JTextField();
        Label_Describe = new javax.swing.JLabel();
        Describe_Fill = new javax.swing.JScrollPane();
        Describe_Mota_Fill = new javax.swing.JTextArea();
        Check_condition = new javax.swing.JCheckBox();
        SignUp_Confirm = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 750));

        White_Panel.setBackground(new java.awt.Color(244, 244, 242));
        White_Panel.setPreferredSize(new java.awt.Dimension(650, 750));

        Label_Information_Fill.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label_Information_Fill.setForeground(new java.awt.Color(0, 102, 102));
        Label_Information_Fill.setText("NHẬP THÔNG TIN KHÁCH SẠN");

        Business_Name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Business_Name.setForeground(new java.awt.Color(0, 0, 0));
        Business_Name.setText("Tên Doanh Nghiệp:");

        Business_Name_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Business_Name_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Business_Name_Fill.setForeground(new java.awt.Color(102, 102, 102));

        Label_Address.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Label_Address.setForeground(new java.awt.Color(0, 0, 0));
        Label_Address.setText("Địa Chỉ:");

        Address_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Address_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Address_Fill.setForeground(new java.awt.Color(102, 102, 102));

        Label_Describe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Label_Describe.setForeground(new java.awt.Color(0, 0, 0));
        Label_Describe.setText("Mô Tả");

        Describe_Mota_Fill.setBackground(new java.awt.Color(249, 249, 249));
        Describe_Mota_Fill.setColumns(20);
        Describe_Mota_Fill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Describe_Mota_Fill.setForeground(new java.awt.Color(102, 102, 102));
        Describe_Mota_Fill.setLineWrap(true);
        Describe_Mota_Fill.setRows(5);
        Describe_Mota_Fill.setWrapStyleWord(true);
        Describe_Fill.setViewportView(Describe_Mota_Fill);

        Check_condition.setBackground(new java.awt.Color(244, 244, 242));
        Check_condition.setForeground(new java.awt.Color(102, 102, 102));
        Check_condition.setText("Đồng ý cung cấp thông tin của tôi trong quá trình sử dụng.");

        SignUp_Confirm.setBackground(new java.awt.Color(0, 102, 102));
        SignUp_Confirm.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SignUp_Confirm.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Confirm.setText("Đăng Ký");
        SignUp_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout White_PanelLayout = new javax.swing.GroupLayout(White_Panel);
        White_Panel.setLayout(White_PanelLayout);
        White_PanelLayout.setHorizontalGroup(
            White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(White_PanelLayout.createSequentialGroup()
                .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(White_PanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Label_Information_Fill))
                    .addGroup(White_PanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Label_Describe)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(White_PanelLayout.createSequentialGroup()
                    .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(White_PanelLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Check_condition)
                                .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Business_Name)
                                    .addComponent(Business_Name_Fill)
                                    .addComponent(Label_Address)
                                    .addComponent(Address_Fill)
                                    .addComponent(Describe_Fill, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))))
                        .addGroup(White_PanelLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(SignUp_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        White_PanelLayout.setVerticalGroup(
            White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(White_PanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(Label_Information_Fill)
                .addGap(181, 181, 181)
                .addComponent(Label_Describe)
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(White_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(White_PanelLayout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(Business_Name)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Business_Name_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Label_Address)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Address_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)
                    .addComponent(Describe_Fill, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Check_condition)
                    .addGap(18, 18, 18)
                    .addComponent(SignUp_Confirm)
                    .addContainerGap(132, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(White_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(White_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ConfirmActionPerformed
        // TODO add your handling code here:
        
        // Lấy thông tin người đăng ký nhập
        this.khachsan.setTENDN(Business_Name_Fill.getText());
        this.khachsan.setDIACHI(Address_Fill.getText());
        this.khachsan.setMOTA(Describe_Mota_Fill.getText());
        
        if (!Check_condition.isSelected()) {
            JOptionPane.showMessageDialog(this,
                "Bạn phải đồng ý với điều khoản để đăng ký!",
                "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (this.khachsan.getTENDN().isEmpty() || this.khachsan.getDIACHI().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Bạn phải điền đầy đủ thông tin!",
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Login_SignUp_Check.InsertDOANHNGHIEP(this.khachsan);
    }//GEN-LAST:event_SignUp_ConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_Fill;
    private javax.swing.JLabel Business_Name;
    private javax.swing.JTextField Business_Name_Fill;
    private javax.swing.JCheckBox Check_condition;
    private javax.swing.JScrollPane Describe_Fill;
    private javax.swing.JTextArea Describe_Mota_Fill;
    private javax.swing.JLabel Label_Address;
    private javax.swing.JLabel Label_Describe;
    private javax.swing.JLabel Label_Information_Fill;
    private javax.swing.JButton SignUp_Confirm;
    private javax.swing.JPanel White_Panel;
    // End of variables declaration//GEN-END:variables
}
