/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Component;

import java.awt.CardLayout;
import javax.swing.JPanel;
import DAO.DonChinhSua_DAO;
import DAO.KhachSan_DAO;
import MODEL.KHACHSAN;
import MODEL.DonChinhSua;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bobui
 */
public class tableDonChinhSua extends javax.swing.JPanel {

    private JPanel parent;
    private CardLayout cardLayout;
    private KHACHSAN ks;
    
    
    
    public tableDonChinhSua(JPanel parent,CardLayout cardLayout, String email) {
        initComponents();
        KhachSan_DAO dao = new KhachSan_DAO();
        this.ks = dao.select(email);
        
        loadTableData(ks.getID());
        
    }

    public void loadTableData(Integer id) {
        DefaultTableModel model = (DefaultTableModel) listdonTable.getModel();
        model.setRowCount(0);
        DonChinhSua_DAO dao = new DonChinhSua_DAO();
        List<DonChinhSua> list = dao.selectDonChinhSuaByKhachSanId(id);
        for (DonChinhSua d : list) {
            model.addRow(new Object[]{
                d.getId(),
                d.getDatPhongId(),
                d.getNgayNhanMoi(),
                d.getNgayTraMoi(),
                d.getSlMoi(),
                d.getTrangThaiDuyet(),
                d.getTrangThaiThanhToan()
            });
        }
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < listdonTable.getColumnCount(); i++) {
            listdonTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        listdonTable = new javax.swing.JTable();

        listdonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn chỉnh sửa", "Mã đơn đặt", "Ngàn nhận mới", "Ngày trả mới", "Số lượng mới", "Trạng thái duyệt", "Trạng thái thanh toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listdonTable.setRowHeight(40);
        jScrollPane2.setViewportView(listdonTable);
        if (listdonTable.getColumnModel().getColumnCount() > 0) {
            listdonTable.getColumnModel().getColumn(0).setResizable(false);
            listdonTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            listdonTable.getColumnModel().getColumn(1).setResizable(false);
            listdonTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            listdonTable.getColumnModel().getColumn(2).setResizable(false);
            listdonTable.getColumnModel().getColumn(3).setResizable(false);
            listdonTable.getColumnModel().getColumn(4).setResizable(false);
            listdonTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            listdonTable.getColumnModel().getColumn(5).setResizable(false);
            listdonTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 225, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1471, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listdonTable;
    // End of variables declaration//GEN-END:variables
}
