/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.JFRAME;

import DAO.DonDat_DAO;
import MODEL.DonChinhSua;
import MODEL.DonDat;
import java.text.SimpleDateFormat;
import java.util.Date;
import utils.message;

/**
 *
 * @author LENOVO
 */
public class CuaSoPheDuyet extends javax.swing.JFrame {

    /**
     * Creates new form CuaSoPheDuyet
     */
    private DonChinhSua dcs=null;
    private DonDat dd=null;
    private int phongcl=0;
    
    public CuaSoPheDuyet() {
        initComponents();
    }

    public CuaSoPheDuyet(DonChinhSua DCS, DonDat DD) {
        initComponents();
        this.dcs=DCS;
        this.dd=DD;
        
        if(dcs!=null){
            SoPhongCu.setText(dd.getSl().toString());
            NgayNhanCu.setText(dd.getNgayNhan().toString());
            NgayTraCu.setText(dd.getNgayTra().toString());
        }
        if(dd!=null){
            SoPhongMoi.setText(String.valueOf(dcs.getSlMoi()));
            NgayNhanMoi.setText(dcs.getNgayNhanMoi().toString());
            NgayTraMoi.setText(dcs.getNgayTraMoi().toString());
        }
        
        Date date1 = dcs.getNgayNhanMoi();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate1 = sdf1.format(date1);
        
        Date date2 = dcs.getNgayTraMoi();
        SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate2 = sdf2.format(date2);
        
        phongcl=DonDat_DAO.checkSLC(dd.getIdP(), formattedDate1, formattedDate2);
        
        if (phongcl>=dcs.getSlMoi()){
            LabelTB.setText("Số phòng còn trống lúc đó: "+ phongcl +" . Thỏa yêu cầu sửa đổi! ");
        } else{
            LabelTB.setText("Số phòng còn trống lúc đó: "+ phongcl +" . Không thỏa yêu cầu sửa đổi! ");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TieuDe = new javax.swing.JLabel();
        label_Cu1 = new javax.swing.JLabel();
        label_Moi1 = new javax.swing.JLabel();
        SoPhongCu = new javax.swing.JLabel();
        SoPhongMoi = new javax.swing.JLabel();
        label_Cu2 = new javax.swing.JLabel();
        NgayNhanCu = new javax.swing.JLabel();
        label_Moi2 = new javax.swing.JLabel();
        NgayNhanMoi = new javax.swing.JLabel();
        label_Cu3 = new javax.swing.JLabel();
        NgayTraCu = new javax.swing.JLabel();
        Label_Moi3 = new javax.swing.JLabel();
        NgayTraMoi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LabelTB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel1.setBackground(new java.awt.Color(244, 244, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setRequestFocusEnabled(false);

        TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TieuDe.setForeground(new java.awt.Color(0, 102, 102));
        TieuDe.setText("So Sánh Thông Tin Yêu Cầu Sửa");

        label_Cu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Cu1.setForeground(new java.awt.Color(0, 0, 0));
        label_Cu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Cu1.setText("Số Lượng Phòng Cũ:");

        label_Moi1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Moi1.setForeground(new java.awt.Color(0, 0, 0));
        label_Moi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Moi1.setText("Số Lượng Phòng Mới:");

        SoPhongCu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SoPhongCu.setForeground(new java.awt.Color(0, 0, 0));
        SoPhongCu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SoPhongCu.setText("VD: 5");

        SoPhongMoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SoPhongMoi.setForeground(new java.awt.Color(0, 0, 0));
        SoPhongMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SoPhongMoi.setText("VD: 5");

        label_Cu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Cu2.setForeground(new java.awt.Color(0, 0, 0));
        label_Cu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Cu2.setText("Ngày Nhận Phòng Cũ:");

        NgayNhanCu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NgayNhanCu.setForeground(new java.awt.Color(0, 0, 0));
        NgayNhanCu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NgayNhanCu.setText("VD: 5");

        label_Moi2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Moi2.setForeground(new java.awt.Color(0, 0, 0));
        label_Moi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Moi2.setText("Ngày Nhận Phòng Mới:");

        NgayNhanMoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NgayNhanMoi.setForeground(new java.awt.Color(0, 0, 0));
        NgayNhanMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NgayNhanMoi.setText("VD: 5");

        label_Cu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Cu3.setForeground(new java.awt.Color(0, 0, 0));
        label_Cu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Cu3.setText("Ngày Trả Phòng Cũ:");

        NgayTraCu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NgayTraCu.setForeground(new java.awt.Color(0, 0, 0));
        NgayTraCu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NgayTraCu.setText("VD: 5");

        Label_Moi3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Moi3.setForeground(new java.awt.Color(0, 0, 0));
        Label_Moi3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Moi3.setText("Ngày Trả Phòng Mới:");

        NgayTraMoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NgayTraMoi.setForeground(new java.awt.Color(0, 0, 0));
        NgayTraMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NgayTraMoi.setText("VD: 5");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Duyệt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Không Duyệt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Hoặc");

        LabelTB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTB.setForeground(new java.awt.Color(0, 102, 102));
        LabelTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTB.setText("Số phòng còn lại ước tính: ... . Thỏa/ Không thỏa yêu cầu sửa đổi! ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SoPhongCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Cu2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(label_Cu1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(label_Cu3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(NgayNhanCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NgayTraCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(220, 220, 220)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_Moi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Moi2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Label_Moi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NgayTraMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NgayNhanMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SoPhongMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(TieuDe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(LabelTB, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cu1)
                    .addComponent(label_Moi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoPhongCu)
                    .addComponent(SoPhongMoi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Cu2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NgayNhanCu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Moi2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NgayNhanMoi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Cu3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NgayTraCu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Moi3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NgayTraMoi)))
                .addGap(27, 27, 27)
                .addComponent(LabelTB)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (phongcl<dcs.getSlMoi()){
            message.alert(null, "Không đủ phòng!");
            return;
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuaSoPheDuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuaSoPheDuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuaSoPheDuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuaSoPheDuyet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuaSoPheDuyet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTB;
    private javax.swing.JLabel Label_Moi3;
    private javax.swing.JLabel NgayNhanCu;
    private javax.swing.JLabel NgayNhanMoi;
    private javax.swing.JLabel NgayTraCu;
    private javax.swing.JLabel NgayTraMoi;
    private javax.swing.JLabel SoPhongCu;
    private javax.swing.JLabel SoPhongMoi;
    private javax.swing.JLabel TieuDe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_Cu1;
    private javax.swing.JLabel label_Cu2;
    private javax.swing.JLabel label_Cu3;
    private javax.swing.JLabel label_Moi1;
    private javax.swing.JLabel label_Moi2;
    // End of variables declaration//GEN-END:variables
}
