package GUI.JFRAME;

import java.sql.*;
import java.util.Vector;
import java.util.Hashtable;
import javax.swing.table.DefaultTableModel;
import database.jdbcHelper;
import MODEL.Phong_KS;
import DAO.PhongKS_DAO;
import GUI.Component.CustomScrollBar;
import GUI.Component.DashBoard;
import GUI.Component.HomePage;
import GUI.Component.tableDonChinhSua;
import java.lang.Integer;
import java.lang.Long;
import utils.message;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import GUI.Component.tableDonDat;
import GUI.Component.tablePhongKS;
import javax.swing.JOptionPane;
import MODEL.NGUOIDUNG;
import java.awt.CardLayout;

public class Menu_KhachSan extends javax.swing.JFrame {
    
    private CardLayout cardLayout;
    private tablePhongKS table;
    private DashBoard dashBoard;
    private HomePage homePage;
    private tableDonChinhSua dcs;
    
    private Integer idKS;
    private NGUOIDUNG user;
    private int selectedRow=-1;
    
    private int selectedPhongID = -1; //1 phần của chức năng thêm ảnh
    
    
//    OracleDataBase_Connection my_conn = new OracleDataBase_Connection();
//    Connection conn = null;
    
    public Menu_KhachSan() {
        initComponents();
    }
    
    public Menu_KhachSan(NGUOIDUNG user){
        new jdbcHelper("booking_app", "12345678");
        this.idKS = user.getID();
        System.out.println(this.idKS);
        this.user = user;
        initComponents();
        initCardLayout();
        YourEmail.setText(user.getEMAIL());
    }
    
    public void initCardLayout(){
        content.setLayout(new CardLayout());
        this.cardLayout = (CardLayout) content.getLayout();
        
        dashBoard = new DashBoard();
        table = new tablePhongKS(this.user);
        homePage = new HomePage(this.user);
        dcs = new tableDonChinhSua(content, this.cardLayout,this.user.getEMAIL());
        System.out.print(this.user.getEMAIL());
        
        content.add(dcs,"tabledcs");
        content.add(table, "table");
        content.add(dashBoard, "dashBoard");
        content.add(homePage, "Home Page");
        
        cardLayout.show(content, "table");
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashBoard = new javax.swing.JPanel();
        UserIcon = new javax.swing.JLabel();
        ManageBtn = new javax.swing.JButton();
        AccountBtn = new javax.swing.JButton();
        YourEmail = new javax.swing.JLabel();
        dcsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashBoard.setBackground(new java.awt.Color(0, 102, 102));
        DashBoard.setPreferredSize(new java.awt.Dimension(300, 1025));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account_circle.png"))); // NOI18N

        ManageBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        ManageBtn.setForeground(new java.awt.Color(0, 102, 102));
        ManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bad (1).png"))); // NOI18N
        ManageBtn.setText("Quản Lý Phòng");
        ManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBtnActionPerformed(evt);
            }
        });

        AccountBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        AccountBtn.setForeground(new java.awt.Color(0, 102, 102));
        AccountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        AccountBtn.setText("Tài Khoản");
        AccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBtnActionPerformed(evt);
            }
        });

        YourEmail.setForeground(new java.awt.Color(255, 255, 255));
        YourEmail.setText("Your Email");

        dcsBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        dcsBtn.setForeground(new java.awt.Color(0, 102, 102));
        dcsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        dcsBtn.setText("Quản Lý Đơn sửa");
        dcsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcsBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 102, 102));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout_1.png"))); // NOI18N
        logoutBtn.setText("Đăng xuất");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(UserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YourEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(AccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(ManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(YourEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addComponent(ManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(dcsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(AccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(429, 429, 429)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setMaximumSize(new java.awt.Dimension(32767, 1000000000));
        content.setPreferredSize(new java.awt.Dimension(1320, 1025));
        content.setRequestFocusEnabled(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1414, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 1414, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBtnActionPerformed
        // TODO add your handling code here:
        cardLayout.show(content, "table");
    }//GEN-LAST:event_ManageBtnActionPerformed

    private void AccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBtnActionPerformed

    }//GEN-LAST:event_AccountBtnActionPerformed

    private void dcsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcsBtnActionPerformed
        // TODO add your handling code here:
        cardLayout.show(content, "tabledcs");
    }//GEN-LAST:event_dcsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // Mở màn hình đăng nhập
        Main_Login_Register_JF login = new Main_Login_Register_JF();
        login.pack();
        login.setLocationRelativeTo(null);//Hiện ở giữa màn hình
        login.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_KhachSan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountBtn;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JButton ManageBtn;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel YourEmail;
    private javax.swing.JPanel content;
    private javax.swing.JButton dcsBtn;
    private javax.swing.JButton logoutBtn;
    // End of variables declaration//GEN-END:variables
}
