package GUI.JFRAME;

import DAO.PhongKS_DAO;
import MODEL.NGUOIDUNG;
import MODEL.Phong_KS;
import database.Oracle_connection;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.CreateAnimationLabels;

/**
 *
 * @author Admin
 */
public class TaoPhong extends javax.swing.JFrame {

    /**
     * Creates new form TaoPhong
     */
    private NGUOIDUNG user;
    private Phong_KS phong = null;
    private JTable myTable;
    private PhongKS_DAO phongKSDao = new PhongKS_DAO();
    
    private int phongID;
    private JLabel[] lblAnhs;
   
    private File[] selectedFiles = new File[3];      // Ảnh người dùng chọn mới
    private byte[][] imageLoaded = new byte[3][];    // Ảnh đã load từ DB
    private int selectedIndex = -1; // Ảnh đang được chọn (0 - 2)
    
    public TaoPhong() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public TaoPhong(NGUOIDUNG user) {
        this.user = user;
        initComponents();
        configLabelAnh();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public TaoPhong(NGUOIDUNG user, Phong_KS phong) {
        this.user = user;
        this.phong = phong;
        this.phongID = phong.getId();
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        configLabelAnh();
        setTextField(phong);
    }
    
    public void configLabelAnh(){
        lblAnhs = new JLabel[]{this.anh1, this.anh2, this.anh3};//Tên label bạn đặt trong UI
        this.anh1 = CreateAnimationLabels.createInteractiveLabel(this.anh1);
        this.anh2 = CreateAnimationLabels.createInteractiveLabel(this.anh2);
        this.anh3 = CreateAnimationLabels.createInteractiveLabel(this.anh3);
        for (int i = 0; i < lblAnhs.length; i++) {
            final int index = i;
            lblAnhs[i].addMouseListener(new MouseAdapter() {
              
                public void mouseClicked(MouseEvent e) {
                    selectedIndex = index;
                }
            });
        }
        
        
        btnAddImg.addActionListener(e ->chonAnh());
        btnUpdateImg.addActionListener(e ->chonAnh());
        btnDeleteImg.addActionListener(e -> xoaAnh());
        
        loadAnhTuDatabase();
    }
    
    public void setTextField(Phong_KS phong){
        if (phong != null){
            txtLoaiPhong.setText(phong.getLoaiPhong());
            txtGia.setText(String.valueOf(phong.getGia()));
            txtSoLuong.setText(String.valueOf(phong.getTongSoluong()));
            txtMoTa.setText(String.valueOf(phong.getMoTa()));
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        anh1 = new javax.swing.JLabel();
        anh2 = new javax.swing.JLabel();
        anh3 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnDeleteImg = new javax.swing.JButton();
        btnUpdateImg = new javax.swing.JButton();
        btnAddImg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(244, 244, 242));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thông tin phòng");

        jPanel2.setBackground(new java.awt.Color(244, 244, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Loại phòng: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Giá: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Số lượng:");

        txtLoaiPhong.setBackground(new java.awt.Color(249, 249, 249));
        txtLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiPhongActionPerformed(evt);
            }
        });

        txtGia.setBackground(new java.awt.Color(249, 249, 249));
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        txtSoLuong.setBackground(new java.awt.Color(249, 249, 249));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Mô tả: ");

        txtMoTa.setBackground(new java.awt.Color(255, 255, 255));
        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        jPanel3.setBackground(new java.awt.Color(244, 244, 242));
        jPanel3.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        anh1.setBackground(new java.awt.Color(255, 255, 255));
        anh1.setForeground(new java.awt.Color(0, 0, 0));
        anh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        anh1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(anh1);

        anh2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(anh2);

        anh3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(anh3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                        .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnCreate.setBackground(new java.awt.Color(0, 102, 102));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(244, 244, 242));
        btnCreate.setText("Xác nhận");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDeleteImg.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteImg.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnDeleteImg.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteImg.setText("Xóa ảnh");
        btnDeleteImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteImgActionPerformed(evt);
            }
        });

        btnUpdateImg.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateImg.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnUpdateImg.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateImg.setText("Sửa ảnh");
        btnUpdateImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateImgActionPerformed(evt);
            }
        });

        btnAddImg.setBackground(new java.awt.Color(255, 255, 255));
        btnAddImg.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAddImg.setForeground(new java.awt.Color(0, 0, 0));
        btnAddImg.setText("Thêm ảnh");
        btnAddImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAddImg)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateImg)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreate))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteImg)
                        .addComponent(btnUpdateImg)
                        .addComponent(btnAddImg))
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void chonAnh() {
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Hãy click vào 1 ảnh để chọn.");
            return;
        }
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFiles[selectedIndex] = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(
                new ImageIcon(selectedFiles[selectedIndex].getAbsolutePath())
                .getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)
            );
            lblAnhs[selectedIndex].setIcon(icon);
            lblAnhs[selectedIndex].setText("");
        }
    }
    
    
    private void xoaAnh() {
        if (selectedIndex == -1) {
        JOptionPane.showMessageDialog(this, "Hãy chọn ảnh cần xóa.");
        return;
    }
        selectedFiles[selectedIndex] = null;
        imageLoaded[selectedIndex] = null;
        lblAnhs[selectedIndex].setIcon(null);
        lblAnhs[selectedIndex].setText("Ảnh " + (selectedIndex + 1));
    }
    
    private void luuAnhVaoDB() {
        try (Connection conn = Oracle_connection.getConnection("booking_app", "12345678")) {
            String sql = "UPDATE PHONG SET ANH1 = ?, ANH2 = ?, ANH3 = ? WHERE ID = ?";
            PreparedStatement ps = conn.prepareStatement(sql);

            for (int i = 0; i < 3; i++) {
                if (selectedFiles[i] != null) {
                    FileInputStream fis = new FileInputStream(selectedFiles[i]);
                    ps.setBinaryStream(i + 1, fis, (int) selectedFiles[i].length());
                } else if (imageLoaded[i] != null) {
                    ps.setBinaryStream(i + 1, new ByteArrayInputStream(imageLoaded[i]), imageLoaded[i].length);
                } else {
                    ps.setNull(i + 1, java.sql.Types.BLOB);
                }
            }
            ps.setInt(4, phongID);

            int rows = ps.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Đã cập nhật ảnh thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy phòng để cập nhật.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu ảnh.");
        }
    }
    
    private void loadAnhTuDatabase() {
        try (Connection conn = Oracle_connection.getConnection("booking_app", "12345678")) {
            String sql = "SELECT ANH1, ANH2, ANH3 FROM PHONG WHERE ID = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, phongID);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Blob[] blobs = new Blob[3];
                blobs[0] = rs.getBlob("ANH1");
                blobs[1] = rs.getBlob("ANH2");
                blobs[2] = rs.getBlob("ANH3");

                for (int i = 0; i < 3; i++) {
                    if (blobs[i] != null) {
                        byte[] imageData = blobs[i].getBytes(1, (int) blobs[i].length());
                        imageLoaded[i] = imageData; // <- Lưu dữ liệu ảnh để sau này có thể giữ lại nếu người dùng không sửa
                        
                        BufferedImage img = ImageIO.read(new ByteArrayInputStream(imageData));
                        ImageIcon icon = new ImageIcon(
                            img.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
                        lblAnhs[i].setIcon(icon);
                        lblAnhs[i].setText("");
                    } else {
                        lblAnhs[i].setIcon(null);
                        lblAnhs[i].setText("Ảnh " + (i + 1));
                    }
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Không thể tải ảnh từ database.");
        }
    }
    
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        Integer idKS = this.user.getID();
        String loaiPhong = txtLoaiPhong.getText();
        String moTa = txtMoTa.getText();
        Long gia = Long.valueOf(txtGia.getText());
        Long sl = Long.valueOf(txtSoLuong.getText());
        LocalDate today = LocalDate.now();
        Phong_KS phong = new Phong_KS(null, idKS, loaiPhong, moTa, gia, sl,  today);
        if (this.phong != null){
            phong.setId(this.phong.getId());
            phongKSDao.update(phong);
        }
        else{
           this.phongID = phongKSDao.insertAndReturnID(phong);
           this.luuAnhVaoDB();
        }
        this.phong = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiPhongActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnDeleteImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteImgActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.phong = null;
    }//GEN-LAST:event_formWindowClosing

    private void btnUpdateImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateImgActionPerformed

    private void btnAddImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anh1;
    private javax.swing.JLabel anh2;
    private javax.swing.JLabel anh3;
    private javax.swing.JButton btnAddImg;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDeleteImg;
    private javax.swing.JButton btnUpdateImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
