/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.JFRAME;

import DAO.DonDat_DAO;
import DAO.ThanhToan_Dao;
import MODEL.DonChinhSua;
import MODEL.DonDat;
import MODEL.ThanhToan_model;
import PDF.HoaDonPDF;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ThanhToanThem extends javax.swing.JFrame {

    /**
     * Creates new form ThanhToanThem
     */
    private ThanhToan_model tt_model;
    private DonDat donDat;
    private DonChinhSua dcs;
    
    public ThanhToanThem() {
        initComponents();
    }

    public ThanhToanThem(DonChinhSua DCS, DonDat DD, long STC){
        initComponents();
        this.dcs = DCS;
        this.donDat=DD;
        
        long millisDiff = dcs.getNgayTraMoi().getTime() - dcs.getNgayNhanMoi().getTime();
        long daysDiff = millisDiff / (1000 * 60 * 60 * 24);
        
        long GiaMoi=daysDiff * DonDat_DAO.GiaPhong(DD.getIdP()) * dcs.getSlMoi();
        
        this.tt_model = new ThanhToan_model(dcs.getDatPhongId(), GiaMoi);

        label_hienthisotien.setText(String.valueOf(GiaMoi-STC)+" VND.");
        
        donDat.setSl(dcs.getSlMoi());
        donDat.setNgayNhan(dcs.getNgayNhanMoi());
        donDat.setNgayTra(dcs.getNgayTraMoi());
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        tieude = new javax.swing.JLabel();
        CardType = new javax.swing.JComboBox<>();
        label_tenchuthe = new javax.swing.JLabel();
        textfield_chuthe = new javax.swing.JTextField();
        label_sothe = new javax.swing.JLabel();
        textfield_sothe = new javax.swing.JTextField();
        textfield_ngayhethan = new javax.swing.JTextField();
        label_ngayhethan = new javax.swing.JLabel();
        label_loaithe = new javax.swing.JLabel();
        label_maPin = new javax.swing.JLabel();
        textfield_maPin = new javax.swing.JPasswordField();
        label_sotien = new javax.swing.JLabel();
        label_hienthisotien = new javax.swing.JLabel();
        cauhoixacnhan = new javax.swing.JLabel();
        xacnhan_button = new javax.swing.JButton();
        label_hoac = new javax.swing.JLabel();
        huy_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGround.setBackground(new java.awt.Color(244, 244, 242));
        BackGround.setPreferredSize(new java.awt.Dimension(750, 650));

        tieude.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tieude.setForeground(new java.awt.Color(0, 102, 102));
        tieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieude.setText("Nhập Thông Tin Thanh Toán Thêm");

        CardType.setBackground(new java.awt.Color(249, 249, 249));
        CardType.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CardType.setForeground(new java.awt.Color(51, 51, 51));
        CardType.setMaximumRowCount(10);
        CardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa", "Mastercard", "JCB", "ABBANK", "ACB", "ANZ VL", "Agribank", "BAOVIET Bank", "Bac A Bank", "BVBank", "BIDV", "CIMB", "Co-opBank", "DongA Bank", "Eximbank", "GPBank", "HLB VN", "HDBank", "HSBC", "IVB", "KienlongBank", "LienVietPostBank", "MB Bank", "MBV", "MSB", "Nam A Bank", "NCB", "OCB", "PBVN", "PGBank", "PVcomBank", "Sacombank", "SAIGONBANK", "SCB", "SCB VL", "SeABank", "SHB", "SHB VN", "Techcombank", "TPBank", "UOB", "VDB", "VCB Neo", "VIB", "VietABank", "VietCapitalBank", "Vietcombank", "VietinBank", "Vietbank", "VPBank", "VRB", "Woori Bank", "VBSP" }));
        CardType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CardType.setVerifyInputWhenFocusTarget(false);
        CardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardTypeActionPerformed(evt);
            }
        });

        label_tenchuthe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_tenchuthe.setForeground(new java.awt.Color(0, 0, 0));
        label_tenchuthe.setText("Tên Chủ Thẻ:");

        textfield_chuthe.setBackground(new java.awt.Color(249, 249, 249));
        textfield_chuthe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfield_chuthe.setForeground(new java.awt.Color(51, 51, 51));

        label_sothe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_sothe.setForeground(new java.awt.Color(0, 0, 0));
        label_sothe.setText("Số Thẻ:");

        textfield_sothe.setBackground(new java.awt.Color(249, 249, 249));
        textfield_sothe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfield_sothe.setForeground(new java.awt.Color(51, 51, 51));

        textfield_ngayhethan.setBackground(new java.awt.Color(249, 249, 249));
        textfield_ngayhethan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfield_ngayhethan.setForeground(new java.awt.Color(102, 102, 102));
        textfield_ngayhethan.setText("MM/YY");
        textfield_ngayhethan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_ngayhethanMouseClicked(evt);
            }
        });
        textfield_ngayhethan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_ngayhethanActionPerformed(evt);
            }
        });

        label_ngayhethan.setBackground(new java.awt.Color(0, 0, 0));
        label_ngayhethan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_ngayhethan.setForeground(new java.awt.Color(0, 0, 0));
        label_ngayhethan.setText("Ngày Hết Hạn:");

        label_loaithe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_loaithe.setForeground(new java.awt.Color(0, 0, 0));
        label_loaithe.setText("Loại Thẻ:");

        label_maPin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_maPin.setForeground(new java.awt.Color(0, 0, 0));
        label_maPin.setText("CCV / CVC / PIN:");

        textfield_maPin.setBackground(new java.awt.Color(249, 249, 249));
        textfield_maPin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        textfield_maPin.setForeground(new java.awt.Color(51, 51, 51));
        textfield_maPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_maPinActionPerformed(evt);
            }
        });

        label_sotien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_sotien.setForeground(new java.awt.Color(0, 0, 0));
        label_sotien.setText("Số Tiền Cần Thanh Toán:");

        label_hienthisotien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_hienthisotien.setForeground(new java.awt.Color(51, 51, 51));
        label_hienthisotien.setText("vd: 1.000.000");

        cauhoixacnhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cauhoixacnhan.setForeground(new java.awt.Color(102, 102, 102));
        cauhoixacnhan.setText("Xác nhận thanh toán hóa đơn?");

        xacnhan_button.setBackground(new java.awt.Color(0, 102, 102));
        xacnhan_button.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        xacnhan_button.setForeground(new java.awt.Color(255, 255, 255));
        xacnhan_button.setText("Xác Nhận");
        xacnhan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhan_buttonActionPerformed(evt);
            }
        });

        label_hoac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_hoac.setForeground(new java.awt.Color(102, 102, 102));
        label_hoac.setText("Hoặc");

        huy_button.setBackground(new java.awt.Color(255, 255, 255));
        huy_button.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        huy_button.setForeground(new java.awt.Color(0, 102, 102));
        huy_button.setText("Hủy");
        huy_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huy_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackGroundLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cauhoixacnhan)
                            .addGroup(BackGroundLayout.createSequentialGroup()
                                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                                        .addComponent(label_hoac)
                                        .addGap(63, 63, 63))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(huy_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(xacnhan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))
                            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textfield_chuthe)
                                .addComponent(label_sothe)
                                .addComponent(textfield_sothe)
                                .addComponent(label_tenchuthe)
                                .addComponent(label_sotien)
                                .addComponent(label_hienthisotien, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_ngayhethan)
                            .addComponent(CardType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textfield_ngayhethan)
                            .addComponent(label_loaithe)
                            .addComponent(label_maPin)
                            .addComponent(textfield_maPin))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(tieude)
                .addGap(52, 52, 52)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sothe)
                    .addComponent(label_loaithe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_sothe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tenchuthe)
                    .addComponent(label_ngayhethan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfield_ngayhethan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(textfield_chuthe, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_sotien)
                    .addComponent(label_maPin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_maPin)
                    .addComponent(label_hienthisotien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(cauhoixacnhan)
                .addGap(18, 18, 18)
                .addComponent(xacnhan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_hoac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(huy_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardTypeActionPerformed

    private void textfield_ngayhethanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_ngayhethanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_ngayhethanMouseClicked

    private void textfield_ngayhethanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_ngayhethanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_ngayhethanActionPerformed

    private void textfield_maPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_maPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_maPinActionPerformed

    private void xacnhan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhan_buttonActionPerformed
        // TODO add your handling code here:

        String tenchuthe = textfield_chuthe.getText().trim();
        String sothe = textfield_sothe.getText().trim();
        String last4=sothe.substring(sothe.length()-4);
        String tenthe=((String) CardType.getSelectedItem()).trim();

        String ngayhethan=textfield_ngayhethan.getText().trim();
        String maPin=new String(textfield_maPin.getPassword()).trim();

        if (tenchuthe.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên chủ thẻ.");
            return;
        }

        //        if (!sothe.matches("\\d{16,19}")) {
            //            JOptionPane.showMessageDialog(this, "Số thẻ phải gồm từ 16 đến 19 chữ số.");
            //            return;
            //        }

        if (!ngayhethan.matches("\\d{2}/\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Ngày hết hạn phải theo định dạng MM/YY.");
            return;
        } else {
            // Kiểm tra ngày có hợp lệ không
            try {
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("MM/yy");
                java.time.YearMonth thoiHan = java.time.YearMonth.parse(ngayhethan, formatter);
                java.time.YearMonth hienTai = java.time.YearMonth.now();
                if (thoiHan.isBefore(hienTai)) {
                    JOptionPane.showMessageDialog(this, "Thẻ đã hết hạn.");
                    return;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ngày hết hạn không hợp lệ.");
                return;
            }
        }

        if (!maPin.matches("\\d{3,6}")) {
            JOptionPane.showMessageDialog(this, "CVV/CVC/PIN phải từ 3 đến 6 chữ số.");
            return;
        }

        this.tt_model.setChuthe(tenchuthe);
        this.tt_model.setSothe(last4);
        this.tt_model.setTenthe(tenthe);

        ThanhToan_Dao.update(tt_model);
        this.setVisible(false);

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu hóa đơn");
        fileChooser.setSelectedFile(new File("HoaDon_ThanhToan.pdf"));

        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf";
            }

            System.out.println(this.donDat.getNgayDat());
            HoaDonPDF.xuatHoaDonPDF(this.donDat, tenchuthe, tenthe, sothe, tt_model.getSotien(), filePath);

            try {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(new File(filePath));
                }
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Hóa đơn lưu thành công, nhưng không thể mở file PDF.");
            }
        }
    }//GEN-LAST:event_xacnhan_buttonActionPerformed

    private void huy_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huy_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huy_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToanThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToanThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToanThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToanThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToanThem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JComboBox<String> CardType;
    private javax.swing.JLabel cauhoixacnhan;
    private javax.swing.JButton huy_button;
    private javax.swing.JLabel label_hienthisotien;
    private javax.swing.JLabel label_hoac;
    private javax.swing.JLabel label_loaithe;
    private javax.swing.JLabel label_maPin;
    private javax.swing.JLabel label_ngayhethan;
    private javax.swing.JLabel label_sothe;
    private javax.swing.JLabel label_sotien;
    private javax.swing.JLabel label_tenchuthe;
    private javax.swing.JTextField textfield_chuthe;
    private javax.swing.JPasswordField textfield_maPin;
    private javax.swing.JTextField textfield_ngayhethan;
    private javax.swing.JTextField textfield_sothe;
    private javax.swing.JLabel tieude;
    private javax.swing.JButton xacnhan_button;
    // End of variables declaration//GEN-END:variables
}
