package GUI.JFRAME;

import DAO.DonDat_DAO;
import database.jdbcHelper;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;

/**
 *
 * @author Admin
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    
        
    private final String user = "booking_app";
    private final String pass = "12345678";
    private jdbcHelper jdbc = new jdbcHelper(user, pass);
    public ThongKe() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initLineChart();
    }
    

    public void initLineChart(){
       // 2. Tạo dữ liệu 7 ngày gần nhất + số booking (ví dụ ngẫu nhiên)
        List<Date> dates = new ArrayList<>();
        List<Integer> counts = new ArrayList<>();
        Random rnd = new Random();
        for (int i = 7; i > 1; --i) {
            LocalDate date = LocalDate.now().minusDays(i);
            String dateString = String.valueOf(date);
            Date utilDate = Date.from(date
                                .atStartOfDay(ZoneId.systemDefault())
                                .toInstant());
            dates.add(utilDate);
            
            Integer numOrder = DonDat_DAO.countOrderWithDate(dateString);
            System.out.println("Date " + date + " have: " + numOrder);
            counts.add(numOrder); // số ngẫu nhiên từ 20–100
        }

        // 3. Xây Line Chart với XChart
        XYChart bookingChart = new XYChartBuilder()
            .width(400).height(300)
            .title("Đơn đặt phòng trong 7 ngày")
            .xAxisTitle("Ngày")
            .yAxisTitle("Số đơn")
            .build();
        bookingChart.getStyler().setLegendVisible(false);
        bookingChart.getStyler().setDatePattern("dd/MM");
        bookingChart.getStyler().setXAxisLabelRotation(45);
        bookingChart.addSeries("Booking", dates, counts);

        // 4. Nhúng chart vào jPanel1 (ô hàng 1, cột 1)
        pn1.setLayout(new BorderLayout());
        
        XChartPanel<XYChart> chartPanel = new XChartPanel<>(bookingChart);
        pn1.add(chartPanel, BorderLayout.CENTER);
        
//        pn2.add(chartPanel, BorderLayout.CENTER);
//        
//        pn3.add(chartPanel, BorderLayout.CENTER);
//        
//        pn4.add(chartPanel, BorderLayout.CENTER);
        
        

        // 5. jPanel2, jPanel3, jPanel4 có thể dùng tương tự cho các chart khác
        // Ví dụ: jPanel2.add(new XChartPanel<>(anotherChart));
        // … 

        // 6. Cập nhật giao diện
        this.revalidate();
        this.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pn1;
    // End of variables declaration//GEN-END:variables
}
